// Catálogo compartido de plantillas — consumido por digitalizador.html (sugerencias matchTemplate) y plantillas.html (índice navegable)
const FORM_LIBRARY = [
  {id:'asistencia',vertical:'sst',nombre:'Registro de Asistencia a Capacitación',
   keywords:['asistencia','capacitacion','participante','instructor','facilitador','tema','objetivo'],
   campos_clave:[
    {etiqueta:'Nombre completo del participante',tipo:'texto'},
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora de inicio',tipo:'hora_auto'},
    {etiqueta:'Hora de finalización',tipo:'hora_auto'},
    {etiqueta:'Facilitador / Instructor',tipo:'texto'},
    {etiqueta:'Cargo',tipo:'select',opciones:['Operario','Técnico','Profesional','Supervisor','Coordinador','Otro']},
    {etiqueta:'Firma del participante',tipo:'firma'},
    {etiqueta:'¿Completó la capacitación?',tipo:'si_no'},
  ]},
  {id:'inspeccion_sst',vertical:'sst',nombre:'Lista de Verificación SST',
   keywords:['inspeccion','verificacion','sst','seguridad','salud','trabajo','cumple','riesgo','epp','hallazgo'],
   campos_clave:[
    {etiqueta:'Empresa / Establecimiento',tipo:'texto'},{etiqueta:'Fecha de inspección',tipo:'fecha_auto'},
    {etiqueta:'Área inspeccionada',tipo:'select',opciones:['Producción','Almacén','Oficinas','Mantenimiento','Otro']},
    {etiqueta:'Inspector responsable',tipo:'texto'},
    {etiqueta:'Calificación',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'Observaciones / Hallazgos',tipo:'textarea'},{etiqueta:'Acción correctiva',tipo:'textarea'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Firma del inspector',tipo:'firma'},
    {etiqueta:'Ubicación GPS',tipo:'ubicacion'},
  ]},
  {id:'acta_reunion',vertical:'general',nombre:'Acta de Reunión',
   keywords:['reunion','acta','acuerdo','compromiso','asistente','orden del dia','seguimiento','responsable'],
   campos_clave:[
    {etiqueta:'Objeto / Asunto de la reunión',tipo:'texto'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Lugar / Modalidad',tipo:'select',opciones:['Presencial','Virtual','Híbrida']},
    {etiqueta:'Nombre del asistente',tipo:'texto'},
    {etiqueta:'Compromisos / Acuerdos',tipo:'textarea'},{etiqueta:'Responsable del compromiso',tipo:'texto'},
    {etiqueta:'Fecha límite de cumplimiento',tipo:'fecha_auto'},{etiqueta:'Firma del secretario',tipo:'firma'},
  ]},
  {id:'orden_trabajo',vertical:'general',nombre:'Orden de Trabajo / Servicio',
   keywords:['orden','trabajo','servicio','mantenimiento','correctivo','preventivo','tecnico','falla','equipo','actividades realizadas'],
   campos_clave:[
    {etiqueta:'Número de orden',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Cliente / Empresa',tipo:'texto'},
    {etiqueta:'Tipo de mantenimiento',tipo:'select',opciones:['Correctivo','Preventivo','Predictivo','Instalación']},
    {etiqueta:'Descripción del problema',tipo:'textarea'},{etiqueta:'Actividades realizadas',tipo:'textarea'},
    {etiqueta:'Repuestos / Materiales',tipo:'textarea'},{etiqueta:'Técnico responsable',tipo:'texto'},
    {etiqueta:'Fotografía antes',tipo:'foto'},{etiqueta:'Fotografía después',tipo:'foto'},
    {etiqueta:'Firma del cliente',tipo:'firma'},
  ]},
  {id:'evaluacion_desempeno',vertical:'general',nombre:'Evaluación de Desempeño',
   keywords:['desempeno','evaluacion','competencia','indicador','meta','logro','colaborador','periodo','resultado','calificacion'],
   campos_clave:[
    {etiqueta:'Nombre del colaborador',tipo:'texto'},{etiqueta:'Cargo',tipo:'select'},
    {etiqueta:'Área / Departamento',tipo:'select'},{etiqueta:'Periodo evaluado',tipo:'texto'},
    {etiqueta:'Calificación general',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'Logros del periodo',tipo:'textarea'},{etiqueta:'Oportunidades de mejora',tipo:'textarea'},
    {etiqueta:'Plan de desarrollo',tipo:'textarea'},{etiqueta:'Firma del evaluado',tipo:'firma'},
    {etiqueta:'Firma del evaluador',tipo:'firma'},
  ]},
  {id:'visita_comercial',vertical:'general',nombre:'Reporte de Visita Comercial',
   keywords:['visita','comercial','cliente','prospecto','cotizacion','oportunidad','venta','negocio','seguimiento'],
   campos_clave:[
    {etiqueta:'Fecha de visita',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Nombre del cliente / empresa',tipo:'texto'},{etiqueta:'Contacto / Persona atendida',tipo:'texto'},
    {etiqueta:'Teléfono',tipo:'telefono'},{etiqueta:'Correo electrónico',tipo:'email'},
    {etiqueta:'Objetivo de la visita',tipo:'textarea'},
    {etiqueta:'Resultado',tipo:'select',opciones:['Interesado','No interesado','Requiere seguimiento','Cotización enviada','Negocio cerrado']},
    {etiqueta:'Próximos pasos',tipo:'textarea'},{etiqueta:'Ubicación GPS',tipo:'ubicacion'},
    {etiqueta:'Firma del vendedor',tipo:'firma'},
  ]},
  {id:'solicitud_compra',vertical:'general',nombre:'Solicitud de Compra / Pedido',
   keywords:['solicitud','compra','pedido','requisicion','proveedor','cotizacion','articulo','cantidad','precio'],
   campos_clave:[
    {etiqueta:'Número de solicitud',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Solicitante',tipo:'texto'},{etiqueta:'Área / Departamento',tipo:'select'},
    {etiqueta:'Descripción del artículo',tipo:'texto'},{etiqueta:'Cantidad',tipo:'numero'},
    {etiqueta:'Unidad de medida',tipo:'select',opciones:['Unidad','Caja','Kg','Litro','Metro','Paquete']},
    {etiqueta:'Justificación / Uso',tipo:'textarea'},{etiqueta:'Firma del solicitante',tipo:'firma'},
    {etiqueta:'Aprobado por',tipo:'firma'},
  ]},
  {id:'inspeccion_sanitaria',vertical:'alimentos',nombre:'Inspección Sanitaria / Higiene',
   keywords:['sanitaria','higiene','alimento','limpieza','desinfeccion','plagas','temperatura','inocuidad','establecimiento','bpm'],
   campos_clave:[
    {etiqueta:'Nombre del establecimiento',tipo:'texto'},{etiqueta:'Fecha de inspección',tipo:'fecha_auto'},
    {etiqueta:'Tipo de establecimiento',tipo:'select'},{etiqueta:'Temperatura de almacenamiento (°C)',tipo:'numero'},
    {etiqueta:'Condición de limpieza',tipo:'radio',opciones:['Deficiente','Regular','Bueno','Muy Bueno','Excelente']},
    {etiqueta:'¿Control de plagas vigente?',tipo:'si_no'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Firma del inspector',tipo:'firma'},
    {etiqueta:'Ubicación GPS',tipo:'ubicacion'},
  ]},
  {id:'permiso_trabajo',vertical:'sst',nombre:'Permiso de Trabajo',
   keywords:['permiso','altura','espacio confinado','electrico','caliente','riesgo','ats','atp','trabajador'],
   campos_clave:[
    {etiqueta:'Número de permiso',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Hora de finalización',tipo:'hora_auto'},
    {etiqueta:'Tipo de trabajo',tipo:'select',opciones:['Trabajo en altura','Espacio confinado','Trabajo en caliente','Trabajo eléctrico','Otro']},
    {etiqueta:'Descripción del trabajo',tipo:'textarea'},
    {etiqueta:'¿Se realizó análisis de riesgos?',tipo:'si_no'},
    {etiqueta:'EPP requerido',tipo:'checkbox_multi',opciones:['Casco','Guantes','Arnés','Gafas','Botas','Tapabocas']},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del supervisor',tipo:'firma'},
  ]},
  {id:'entrega_recibo',vertical:'general',nombre:'Acta de Entrega / Recibo de Bienes',
   keywords:['entrega','recibo','bien','activo','devolucion','recibido por','entregado por','estado del bien'],
   campos_clave:[
    {etiqueta:'Fecha de entrega',tipo:'fecha_auto'},{etiqueta:'Descripción del bien',tipo:'texto'},
    {etiqueta:'Serial / Código',tipo:'texto'},{etiqueta:'Cantidad',tipo:'numero'},
    {etiqueta:'Estado del bien',tipo:'select',opciones:['Nuevo','Bueno','Regular','Malo']},
    {etiqueta:'Entregado por',tipo:'texto'},{etiqueta:'Recibido por',tipo:'texto'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Fotografía del bien',tipo:'foto'},
    {etiqueta:'Firma de quien entrega',tipo:'firma'},{etiqueta:'Firma de quien recibe',tipo:'firma'},
  ]},
  {id:'incidente_accidente',vertical:'sst',nombre:'Reporte de Incidente / Accidente Laboral',
   keywords:['incidente','accidente','lesion','trabajador','causa','testigo','investigacion','herido','medica'],
   campos_clave:[
    {etiqueta:'Fecha del incidente',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Trabajador involucrado',tipo:'texto'},{etiqueta:'Cargo',tipo:'select'},
    {etiqueta:'Tipo de evento',tipo:'select',opciones:['Incidente','Accidente de trabajo','Enfermedad laboral','Casi accidente']},
    {etiqueta:'Descripción del evento',tipo:'textarea'},{etiqueta:'Causa raíz',tipo:'textarea'},
    {etiqueta:'¿Hubo atención médica?',tipo:'si_no'},{etiqueta:'Días de incapacidad',tipo:'numero'},
    {etiqueta:'Fotografía de la escena',tipo:'foto'},{etiqueta:'Ubicación GPS del incidente',tipo:'ubicacion'},
    {etiqueta:'Firma del jefe inmediato',tipo:'firma'},
  ]},
  {id:'hoja_de_vida',vertical:'general',nombre:'Hoja de Vida / Solicitud de Empleo',
   keywords:['hoja de vida','curriculum','empleo','aspirante','candidato','experiencia','educacion','referencias','salario'],
   campos_clave:[
    {etiqueta:'Nombres y apellidos',tipo:'texto'},{etiqueta:'Número de cédula',tipo:'numero'},
    {etiqueta:'Fecha de nacimiento',tipo:'fecha'},{etiqueta:'Teléfono celular',tipo:'telefono'},
    {etiqueta:'Correo electrónico',tipo:'email'},
    {etiqueta:'Nivel educativo',tipo:'select',opciones:['Bachillerato','Técnico','Tecnólogo','Universitario','Especialización','Maestría']},
    {etiqueta:'Cargo aspirado',tipo:'texto'},{etiqueta:'Experiencia laboral previa',tipo:'textarea'},
    {etiqueta:'Salario aspirado',tipo:'numero'},{etiqueta:'Fotografía',tipo:'foto'},
    {etiqueta:'Firma del aspirante',tipo:'firma'},
  ]},
  {id:'encuesta_satisfaccion',vertical:'general',nombre:'Encuesta de Satisfacción al Cliente',
   keywords:['satisfaccion','encuesta','opinion','calidad del servicio','recomendaria','atencion','experiencia','califique'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Servicio / Producto evaluado',tipo:'texto'},
    {etiqueta:'Calificación general',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'¿Recomendaría nuestro servicio?',tipo:'si_no'},
    {etiqueta:'Aspectos positivos',tipo:'textarea'},{etiqueta:'Aspectos a mejorar',tipo:'textarea'},
    {etiqueta:'Nombre del cliente (opcional)',tipo:'texto'},{etiqueta:'Correo (opcional)',tipo:'email'},
  ]},
  {id:'calibracion',vertical:'general',nombre:'Registro de Calibración / Mantenimiento de Equipos',
   keywords:['calibracion','instrumento','patron','verificacion','tolerancia','medicion','resultado de calibracion'],
   campos_clave:[
    {etiqueta:'Número de registro',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Equipo / Instrumento',tipo:'texto'},{etiqueta:'Serial / Código',tipo:'texto'},
    {etiqueta:'Tipo de mantenimiento',tipo:'select',opciones:['Preventivo','Correctivo','Calibración','Verificación']},
    {etiqueta:'Resultado de la calibración',tipo:'select',opciones:['Conforme','No conforme','Fuera de tolerancia']},
    {etiqueta:'Próxima calibración',tipo:'fecha'},{etiqueta:'Observaciones técnicas',tipo:'textarea'},
    {etiqueta:'Técnico responsable',tipo:'texto'},{etiqueta:'Firma del técnico',tipo:'firma'},
  ]},

  // ── SST Verticales (Ley 1562/2012 · Decreto 1072/2015) ─────────
  {id:'matriz_peligros',vertical:'sst',nombre:'Matriz de Identificación de Peligros y Valoración de Riesgos (GTC-45)',
   keywords:['matriz','peligro','riesgo','gtc','valoracion','control','consecuencia','probabilidad','nivel de riesgo','intervencion'],
   campos_clave:[
    {etiqueta:'Proceso / Actividad',tipo:'texto'},{etiqueta:'Área / Lugar',tipo:'select',opciones:['Producción','Almacén','Oficinas','Mantenimiento','Exteriores','Otro']},
    {etiqueta:'Tipo de peligro',tipo:'select',opciones:['Físico','Químico','Biológico','Biomecánico','Psicosocial','Condiciones de seguridad','Fenómenos naturales']},
    {etiqueta:'Fuente del peligro',tipo:'texto'},{etiqueta:'Descripción del peligro',tipo:'textarea'},
    {etiqueta:'Efectos posibles',tipo:'textarea'},
    {etiqueta:'Nivel de deficiencia',tipo:'radio',opciones:['MA - Muy alto (10)','A - Alto (6)','M - Medio (2)','B - Bajo (0)']},
    {etiqueta:'Nivel de exposición',tipo:'radio',opciones:['EC - Continua (4)','EF - Frecuente (3)','EO - Ocasional (2)','EE - Esporádica (1)']},
    {etiqueta:'Nivel de consecuencia',tipo:'radio',opciones:['Catastrófico (100)','Muy grave (60)','Grave (25)','Leve (10)']},
    {etiqueta:'¿Existen controles actuales?',tipo:'si_no'},{etiqueta:'Medidas de intervención',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha de ejecución',tipo:'fecha_auto'},
    {etiqueta:'Ubicación GPS',tipo:'ubicacion'},{etiqueta:'Fotografía del riesgo',tipo:'foto'},
  ]},

  {id:'acta_copasst',vertical:'sst',nombre:'Acta de Reunión COPASST',
   keywords:['copasst','copasos','comite paritario','representante empleador','representante trabajadores','presidente copasst','secretario copasst','sgsst'],
   campos_clave:[
    {etiqueta:'Número de acta',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Hora de finalización',tipo:'hora_auto'},
    {etiqueta:'Tipo de reunión',tipo:'select',opciones:['Ordinaria mensual','Extraordinaria']},
    {etiqueta:'Presidente del COPASST',tipo:'texto'},{etiqueta:'Secretario del COPASST',tipo:'texto'},
    {etiqueta:'Representante del empleador',tipo:'texto'},{etiqueta:'Representante de los trabajadores',tipo:'texto'},
    {etiqueta:'Orden del día',tipo:'textarea'},{etiqueta:'Temas tratados y decisiones',tipo:'textarea'},
    {etiqueta:'Compromisos / Responsables',tipo:'textarea'},{etiqueta:'Fecha de seguimiento',tipo:'fecha_auto'},
    {etiqueta:'Firma del presidente',tipo:'firma'},{etiqueta:'Firma del secretario',tipo:'firma'},
  ]},

  {id:'entrega_epp',vertical:'sst',nombre:'Entrega de Elementos de Protección Personal (EPP)',
   keywords:['epp','elementos de proteccion personal','dotacion','casco','botas de seguridad','arnés','proteccion personal','kit epp','recibido conforme','entrega dotacion'],
   campos_clave:[
    {etiqueta:'Fecha de entrega',tipo:'fecha_auto'},{etiqueta:'Nombre del trabajador',tipo:'texto'},
    {etiqueta:'Cargo',tipo:'select',opciones:['Operario','Técnico','Supervisor','Coordinador','Inspector','Otro']},
    {etiqueta:'Área',tipo:'select',opciones:['Producción','Almacén','Mantenimiento','Obra','Laboratorio','Otro']},
    {etiqueta:'Elemento de protección entregado',tipo:'select',opciones:['Casco','Guantes de vaqueta','Guantes de nitrilo','Botas de seguridad','Gafas de seguridad','Protección auditiva','Tapabocas','Arnés','Overol','Otro']},
    {etiqueta:'Talla / Referencia',tipo:'texto'},{etiqueta:'Cantidad',tipo:'numero'},
    {etiqueta:'Motivo de entrega',tipo:'select',opciones:['Primera entrega','Reposición por desgaste','Reposición por pérdida','Cambio de cargo']},
    {etiqueta:'Fecha de vencimiento del EPP',tipo:'fecha'},
    {etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma del trabajador (recibí conforme)',tipo:'firma'},
    {etiqueta:'Firma del responsable de entrega',tipo:'firma'},
  ]},

  {id:'investigacion_at',vertical:'sst',nombre:'Investigación de Accidente de Trabajo (Res. 1401/2007)',
   keywords:['causas basicas','causas inmediatas','accion correctiva','plan de accion','factores contribuyentes','causas raiz','resolucion 1401','investigacion de accidente'],
   campos_clave:[
    {etiqueta:'Fecha del accidente',tipo:'fecha_auto'},{etiqueta:'Hora del accidente',tipo:'hora_auto'},
    {etiqueta:'Fecha de investigación',tipo:'fecha_auto'},{etiqueta:'Trabajador accidentado',tipo:'texto'},
    {etiqueta:'Cargo',tipo:'select'},{etiqueta:'ARL',tipo:'select',opciones:['Positiva','Sura','Colmena','Axa Colpatria','Bolívar','Liberty','Otro']},
    {etiqueta:'Días de incapacidad',tipo:'numero'},
    {etiqueta:'Descripción detallada del accidente',tipo:'textarea'},
    {etiqueta:'Causas inmediatas — actos inseguros',tipo:'textarea'},
    {etiqueta:'Causas inmediatas — condiciones inseguras',tipo:'textarea'},
    {etiqueta:'Causas básicas — factores personales',tipo:'textarea'},
    {etiqueta:'Causas básicas — factores del trabajo',tipo:'textarea'},
    {etiqueta:'Plan de acción correctiva',tipo:'textarea'},{etiqueta:'Responsable del plan',tipo:'texto'},
    {etiqueta:'Fecha límite de acción',tipo:'fecha_auto'},{etiqueta:'¿Se reportó a la ARL?',tipo:'si_no'},
    {etiqueta:'Fotografía de la escena',tipo:'foto'},{etiqueta:'Ubicación GPS',tipo:'ubicacion'},
    {etiqueta:'Firma del investigador',tipo:'firma'},{etiqueta:'Firma del representante legal',tipo:'firma'},
  ]},

  {id:'inspeccion_botiquin',vertical:'sst',nombre:'Inspección de Botiquín y Brigada de Emergencias',
   keywords:['botiquin','brigada','emergencia','extintor','primeros auxilios','camilla','kit de emergencia','evacuacion','punto de encuentro'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Área / Ubicación',tipo:'texto'},
    {etiqueta:'Inspector',tipo:'texto'},
    {etiqueta:'¿Botiquín visible y accesible?',tipo:'si_no'},
    {etiqueta:'¿Analgésicos disponibles?',tipo:'si_no'},{etiqueta:'¿Vendas y gasas?',tipo:'si_no'},
    {etiqueta:'¿Antisépticos (alcohol, agua oxigenada)?',tipo:'si_no'},
    {etiqueta:'¿Guantes desechables?',tipo:'si_no'},{etiqueta:'¿Extintor cercano y vigente?',tipo:'si_no'},
    {etiqueta:'Fecha de vencimiento del elemento más próximo a vencer',tipo:'fecha'},
    {etiqueta:'Elementos faltantes o vencidos',tipo:'textarea'},
    {etiqueta:'Observaciones generales',tipo:'textarea'},
    {etiqueta:'Fotografía del botiquín',tipo:'foto'},
    {etiqueta:'Firma del inspector',tipo:'firma'},
  ]},

  {id:'examen_medico_sst',vertical:'sst',nombre:'Remisión / Resultado de Examen Médico Ocupacional',
   keywords:['examen medico','medico ocupacional','profesiograma','aptitud','ingreso','periodico','retiro','apto','restriccion','eps'],
   campos_clave:[
    {etiqueta:'Nombre del trabajador',tipo:'texto'},{etiqueta:'Número de cédula',tipo:'numero'},
    {etiqueta:'Cargo',tipo:'select'},{etiqueta:'Área',tipo:'select'},
    {etiqueta:'Tipo de examen',tipo:'select',opciones:['Ingreso','Periódico','Retiro','Post-incapacidad','Reubicación laboral','Cambio de cargo']},
    {etiqueta:'Fecha de remisión',tipo:'fecha_auto'},{etiqueta:'IPS / Médico ocupacional',tipo:'texto'},
    {etiqueta:'Resultado',tipo:'select',opciones:['Apto','Apto con restricciones','No apto temporalmente','No apto permanentemente']},
    {etiqueta:'Restricciones / Recomendaciones médicas',tipo:'textarea'},
    {etiqueta:'Fecha del próximo examen',tipo:'fecha'},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del responsable SST',tipo:'firma'},
  ]},

  // ── Construcción Verticales (seguridad en obra + control de avance) ──
  {id:'control_acceso_obra',vertical:'construccion',nombre:'Control de Ingreso de Personal y Visitantes a Obra',
   keywords:['ingreso','acceso','obra','visitante','contratista','control de acceso','induccion','epp obligatorio'],
   campos_clave:[
    {etiqueta:'Nombre completo',tipo:'texto'},{etiqueta:'Cédula',tipo:'numero'},
    {etiqueta:'Empresa / Contratista',tipo:'texto'},{etiqueta:'Fecha de ingreso',tipo:'fecha_auto'},
    {etiqueta:'Hora de ingreso',tipo:'hora_auto'},{etiqueta:'Hora de salida',tipo:'hora_auto'},
    {etiqueta:'Motivo de la visita',tipo:'select',opciones:['Trabajo contratado','Visita técnica','Supervisión','Entrega de materiales','Otro']},
    {etiqueta:'¿Recibió inducción de seguridad?',tipo:'si_no'},
    {etiqueta:'EPP verificado',tipo:'checkbox_multi',opciones:['Casco','Botas de seguridad','Chaleco reflectivo','Guantes','Gafas de seguridad']},
    {etiqueta:'Firma de ingreso',tipo:'firma'},
  ]},

  {id:'permiso_altura_obra',vertical:'construccion',nombre:'Permiso de Trabajo en Alturas (Obra)',
   keywords:['trabajo en alturas','andamio','arnes','linea de vida','punto de anclaje','permiso de altura','resolucion 4272'],
   campos_clave:[
    {etiqueta:'Número de permiso',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Hora de finalización',tipo:'hora_auto'},
    {etiqueta:'Trabajador autorizado',tipo:'texto'},
    {etiqueta:'Nivel de riesgo',tipo:'select',opciones:['Riesgo I - Trabajo no rutinario','Riesgo II - Trabajo rutinario']},
    {etiqueta:'Altura de trabajo (m)',tipo:'numero'},
    {etiqueta:'Sistema de protección utilizado',tipo:'select',opciones:['Línea de vida','Andamio certificado','Plataforma elevadora','Línea de anclaje móvil']},
    {etiqueta:'¿Certificado de trabajo en alturas vigente?',tipo:'si_no'},
    {etiqueta:'¿Equipo de protección inspeccionado?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del supervisor de alturas',tipo:'firma'},
  ]},

  {id:'inspeccion_andamios',vertical:'construccion',nombre:'Inspección de Andamios',
   keywords:['andamio','plataforma','base nivelada','barandas','rodapie','anclaje','scaffolding'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Ubicación / Frente de obra',tipo:'texto'},
    {etiqueta:'Tipo de andamio',tipo:'select',opciones:['Tubular','Multidireccional','Colgante','Torre móvil']},
    {etiqueta:'¿Base nivelada y estable?',tipo:'si_no'},
    {etiqueta:'¿Barandas y rodapiés instalados?',tipo:'si_no'},
    {etiqueta:'¿Anclajes asegurados?',tipo:'si_no'},
    {etiqueta:'Tarjeta de inspección visible',tipo:'select',opciones:['Verde - Apto','Roja - No apto']},
    {etiqueta:'Observaciones / Hallazgos',tipo:'textarea'},
    {etiqueta:'Fotografía del andamio',tipo:'foto'},{etiqueta:'Firma del inspector',tipo:'firma'},
  ]},

  {id:'preoperacional_maquinaria',vertical:'construccion',nombre:'Checklist Preoperacional de Maquinaria Pesada',
   keywords:['preoperacional','maquinaria','retroexcavadora','volqueta','grua','vehiculo','equipo pesado','revision diaria'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Tipo de equipo',tipo:'select',opciones:['Retroexcavadora','Volqueta','Grúa','Minicargador','Montacargas','Otro']},
    {etiqueta:'Placa / Identificación',tipo:'texto'},{etiqueta:'Operador',tipo:'texto'},
    {etiqueta:'Kilometraje / Horómetro',tipo:'numero'},
    {etiqueta:'¿Niveles de aceite y refrigerante OK?',tipo:'si_no'},
    {etiqueta:'¿Luces y alarma de reversa funcionando?',tipo:'si_no'},
    {etiqueta:'¿Frenos en buen estado?',tipo:'si_no'},
    {etiqueta:'¿Extintor a bordo y vigente?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Firma del operador',tipo:'firma'},
  ]},

  {id:'bitacora_obra',vertical:'construccion',nombre:'Bitácora Diaria de Obra',
   keywords:['bitacora','avance de obra','registro diario','actividades del dia','personal en obra','clima'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Frente de obra / Actividad',tipo:'texto'},
    {etiqueta:'Clima',tipo:'select',opciones:['Soleado','Nublado','Lluvia','Tormenta']},
    {etiqueta:'Personal en obra',tipo:'numero'},
    {etiqueta:'Actividades ejecutadas',tipo:'textarea'},{etiqueta:'Materiales recibidos',tipo:'textarea'},
    {etiqueta:'Novedades / Incidentes',tipo:'textarea'},{etiqueta:'Fotografía de avance',tipo:'foto'},
    {etiqueta:'Firma del residente de obra',tipo:'firma'},
  ]},

  {id:'inspeccion_seguridad_obra',vertical:'construccion',nombre:'Inspección de Seguridad en Obra',
   keywords:['inspeccion de seguridad','obra','orden y aseo','senalizacion','riesgo locativo','condiciones inseguras'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Frente de obra',tipo:'texto'},
    {etiqueta:'Inspector',tipo:'texto'},
    {etiqueta:'¿Señalización de riesgos visible?',tipo:'si_no'},
    {etiqueta:'¿Orden y aseo adecuados?',tipo:'si_no'},
    {etiqueta:'¿Delimitación de zonas de riesgo?',tipo:'si_no'},
    {etiqueta:'¿EPP utilizado por el personal?',tipo:'si_no'},
    {etiqueta:'Calificación general',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'Hallazgos y acciones correctivas',tipo:'textarea'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Ubicación GPS',tipo:'ubicacion'},
    {etiqueta:'Firma del inspector',tipo:'firma'},
  ]},

  {id:'entrega_avance_obra',vertical:'construccion',nombre:'Acta de Entrega de Avance / Recibo de Obra',
   keywords:['acta de entrega','avance de obra','recibo de obra','porcentaje de avance','interventoria','contratista'],
   campos_clave:[
    {etiqueta:'Número de acta',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Contrato / Proyecto',tipo:'texto'},{etiqueta:'Contratista',tipo:'texto'},
    {etiqueta:'Porcentaje de avance (%)',tipo:'numero'},{etiqueta:'Actividades entregadas',tipo:'textarea'},
    {etiqueta:'¿Cumple con especificaciones técnicas?',tipo:'si_no'},
    {etiqueta:'Observaciones de interventoría',tipo:'textarea'},{etiqueta:'Fotografía de la obra',tipo:'foto'},
    {etiqueta:'Firma del contratista',tipo:'firma'},{etiqueta:'Firma del interventor',tipo:'firma'},
  ]},

  {id:'reporte_no_conformidad_obra',vertical:'construccion',nombre:'Reporte de No Conformidad en Obra',
   keywords:['no conformidad','obra','desviacion','accion correctiva','calidad de obra','reproceso'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Frente de obra',tipo:'texto'},
    {etiqueta:'Descripción de la no conformidad',tipo:'textarea'},
    {etiqueta:'Tipo',tipo:'select',opciones:['Calidad','Seguridad','Ambiental','Cronograma']},
    {etiqueta:'Causa',tipo:'textarea'},{etiqueta:'Acción correctiva propuesta',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha límite de cierre',tipo:'fecha'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Firma de quien reporta',tipo:'firma'},
  ]},

  // ── Alimentos Verticales (INVIMA · HACCP · BPM) ───────────────
  {id:'control_temperatura_haccp',vertical:'alimentos',nombre:'Control de Temperatura HACCP (Refrigeración/Congelación)',
   keywords:['temperatura','refrigeracion','congelacion','haccp','nevera','cuarto frio','punto critico de control'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora de registro',tipo:'hora_auto'},
    {etiqueta:'Equipo / Cuarto frío',tipo:'select',opciones:['Refrigerador 1','Refrigerador 2','Congelador','Cuarto frío','Vitrina']},
    {etiqueta:'Temperatura registrada (°C)',tipo:'numero'},
    {etiqueta:'Rango permitido',tipo:'texto'},
    {etiqueta:'¿Dentro del rango permitido?',tipo:'si_no'},
    {etiqueta:'Acción correctiva si aplica',tipo:'textarea'},
    {etiqueta:'Responsable del registro',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'limpieza_desinfeccion',vertical:'alimentos',nombre:'Registro de Limpieza y Desinfección',
   keywords:['limpieza','desinfeccion','sanitizacion','superficie','utensilios','area de produccion','quimico utilizado'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Área / Equipo',tipo:'select',opciones:['Cocina','Área de producción','Baños','Almacén','Utensilios','Superficies de contacto']},
    {etiqueta:'Producto desinfectante utilizado',tipo:'texto'},{etiqueta:'Concentración',tipo:'texto'},
    {etiqueta:'¿Limpieza realizada conforme al procedimiento?',tipo:'si_no'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'control_plagas',vertical:'alimentos',nombre:'Control de Plagas (MIP)',
   keywords:['plagas','roedores','insectos','mip','manejo integrado de plagas','trampa','cebo','fumigacion'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Empresa de control de plagas',tipo:'texto'},
    {etiqueta:'Tipo de plaga monitoreada',tipo:'select',opciones:['Roedores','Insectos rastreros','Insectos voladores','Otro']},
    {etiqueta:'¿Evidencia de actividad de plagas?',tipo:'si_no'},
    {etiqueta:'Estaciones / trampas revisadas',tipo:'numero'},
    {etiqueta:'Acción tomada',tipo:'select',opciones:['Ninguna','Cebo repuesto','Fumigación','Sellado de puntos de entrada']},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Fotografía de evidencia',tipo:'foto'},
    {etiqueta:'Firma del técnico',tipo:'firma'},
  ]},

  {id:'recepcion_materia_prima',vertical:'alimentos',nombre:'Recepción de Materia Prima / Proveedores',
   keywords:['recepcion','materia prima','proveedor','insumo','fecha de vencimiento','lote','certificado de calidad'],
   campos_clave:[
    {etiqueta:'Fecha de recepción',tipo:'fecha_auto'},{etiqueta:'Proveedor',tipo:'texto'},
    {etiqueta:'Producto recibido',tipo:'texto'},{etiqueta:'Lote',tipo:'texto'},
    {etiqueta:'Cantidad',tipo:'numero'},{etiqueta:'Fecha de vencimiento',tipo:'fecha'},
    {etiqueta:'Temperatura de recepción (°C)',tipo:'numero'},
    {etiqueta:'¿Empaque en buen estado?',tipo:'si_no'},{etiqueta:'¿Cumple con ficha técnica?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Firma de quien recibe',tipo:'firma'},
  ]},

  {id:'trazabilidad_lote',vertical:'alimentos',nombre:'Trazabilidad de Lote / Producto Terminado',
   keywords:['trazabilidad','lote','producto terminado','fecha de produccion','fecha de vencimiento','destino','despacho'],
   campos_clave:[
    {etiqueta:'Fecha de producción',tipo:'fecha_auto'},{etiqueta:'Producto',tipo:'texto'},
    {etiqueta:'Número de lote',tipo:'texto'},{etiqueta:'Cantidad producida',tipo:'numero'},
    {etiqueta:'Fecha de vencimiento',tipo:'fecha'},{etiqueta:'Materias primas utilizadas',tipo:'textarea'},
    {etiqueta:'Destino / Cliente',tipo:'texto'},{etiqueta:'Responsable de producción',tipo:'texto'},
    {etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'capacitacion_manipulacion',vertical:'alimentos',nombre:'Capacitación en Manipulación de Alimentos',
   keywords:['manipulacion de alimentos','carnet de manipulacion','curso','higiene del manipulador','capacitacion sanitaria'],
   campos_clave:[
    {etiqueta:'Nombre del manipulador',tipo:'texto'},{etiqueta:'Cédula',tipo:'numero'},
    {etiqueta:'Cargo',tipo:'select',opciones:['Cocinero','Mesero','Auxiliar de cocina','Operario de producción','Otro']},
    {etiqueta:'Fecha de capacitación',tipo:'fecha_auto'},
    {etiqueta:'Tema de la capacitación',tipo:'select',opciones:['Buenas Prácticas de Manufactura (BPM)','HACCP','Higiene personal','Manejo de alérgenos','Otro']},
    {etiqueta:'Capacitador',tipo:'texto'},{etiqueta:'¿Aprobó la evaluación?',tipo:'si_no'},
    {etiqueta:'Vigencia del carné',tipo:'fecha'},{etiqueta:'Firma del manipulador',tipo:'firma'},
  ]},

  {id:'no_conformidad_invima',vertical:'alimentos',nombre:'No Conformidad y Acción Correctiva (Auditoría INVIMA)',
   keywords:['no conformidad','invima','auditoria','hallazgo','accion correctiva','plan de mejora','acta de visita'],
   campos_clave:[
    {etiqueta:'Fecha de la auditoría',tipo:'fecha_auto'},
    {etiqueta:'Tipo de auditoría',tipo:'select',opciones:['INVIMA','Interna','Cliente','Certificación']},
    {etiqueta:'Hallazgo / No conformidad',tipo:'textarea'},
    {etiqueta:'Clasificación',tipo:'select',opciones:['Crítica','Mayor','Menor','Observación']},
    {etiqueta:'Causa raíz',tipo:'textarea'},{etiqueta:'Acción correctiva',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha límite de cierre',tipo:'fecha'},
    {etiqueta:'Evidencia fotográfica',tipo:'foto'},{etiqueta:'Firma del responsable de calidad',tipo:'firma'},
  ]},

  // ── Salud Verticales (clínicas, IPS, laboratorios) ────────────
  {id:'triage_urgencias',vertical:'salud',nombre:'Triage de Urgencias',
   keywords:['triage','urgencias','clasificacion','prioridad','paciente','signos vitales','motivo de consulta'],
   campos_clave:[
    {etiqueta:'Nombre del paciente',tipo:'texto'},{etiqueta:'Documento de identidad',tipo:'numero'},
    {etiqueta:'Fecha de ingreso',tipo:'fecha_auto'},{etiqueta:'Hora de ingreso',tipo:'hora_auto'},
    {etiqueta:'Motivo de consulta',tipo:'textarea'},
    {etiqueta:'Presión arterial',tipo:'texto'},{etiqueta:'Frecuencia cardíaca',tipo:'numero'},
    {etiqueta:'Frecuencia respiratoria',tipo:'numero'},{etiqueta:'Temperatura (°C)',tipo:'numero'},
    {etiqueta:'Saturación de oxígeno (%)',tipo:'numero'},
    {etiqueta:'Nivel de triage',tipo:'select',opciones:['I - Resucitación','II - Emergencia','III - Urgencia','IV - Urgencia menor','V - No urgencia']},
    {etiqueta:'Profesional que clasifica',tipo:'texto'},{etiqueta:'Firma del profesional',tipo:'firma'},
  ]},

  {id:'consentimiento_informado',vertical:'salud',nombre:'Consentimiento Informado',
   keywords:['consentimiento informado','procedimiento','riesgos','autorizacion','paciente','representante legal'],
   campos_clave:[
    {etiqueta:'Nombre del paciente',tipo:'texto'},{etiqueta:'Documento de identidad',tipo:'numero'},
    {etiqueta:'Procedimiento a realizar',tipo:'texto'},{etiqueta:'Médico tratante',tipo:'texto'},
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'¿Riesgos explicados al paciente?',tipo:'si_no'},
    {etiqueta:'¿Paciente autoriza el procedimiento?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma del paciente / representante',tipo:'firma'},{etiqueta:'Firma del médico',tipo:'firma'},
  ]},

  {id:'historia_clinica_ingreso',vertical:'salud',nombre:'Historia Clínica — Ingreso',
   keywords:['historia clinica','ingreso','antecedentes','anamnesis','examen fisico','diagnostico'],
   campos_clave:[
    {etiqueta:'Nombre del paciente',tipo:'texto'},{etiqueta:'Documento de identidad',tipo:'numero'},
    {etiqueta:'Fecha de ingreso',tipo:'fecha_auto'},{etiqueta:'Edad',tipo:'numero'},
    {etiqueta:'Motivo de consulta',tipo:'textarea'},{etiqueta:'Antecedentes personales',tipo:'textarea'},
    {etiqueta:'Antecedentes familiares',tipo:'textarea'},{etiqueta:'Examen físico',tipo:'textarea'},
    {etiqueta:'Diagnóstico',tipo:'textarea'},{etiqueta:'Plan de manejo',tipo:'textarea'},
    {etiqueta:'Médico responsable',tipo:'texto'},{etiqueta:'Firma del médico',tipo:'firma'},
  ]},

  {id:'esterilizacion_equipos',vertical:'salud',nombre:'Control de Esterilización de Equipos e Instrumental',
   keywords:['esterilizacion','autoclave','instrumental','indicador biologico','indicador quimico','lote de esterilizacion'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Equipo / Autoclave',tipo:'texto'},
    {etiqueta:'Número de lote',tipo:'texto'},
    {etiqueta:'Tipo de carga',tipo:'select',opciones:['Instrumental quirúrgico','Textiles','Material de curación','Otro']},
    {etiqueta:'Temperatura alcanzada (°C)',tipo:'numero'},{etiqueta:'Tiempo de exposición (min)',tipo:'numero'},
    {etiqueta:'¿Indicador químico correcto?',tipo:'si_no'},{etiqueta:'¿Indicador biológico correcto?',tipo:'si_no'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'manejo_residuos_hospitalarios',vertical:'salud',nombre:'Manejo de Residuos Hospitalarios (PGIRASA)',
   keywords:['residuos hospitalarios','pgirasa','peligrosos','cortopunzante','anatomopatologico','recoleccion','segregacion'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Área generadora',tipo:'select',opciones:['Urgencias','Hospitalización','Cirugía','Laboratorio','Consulta externa','Otro']},
    {etiqueta:'Tipo de residuo',tipo:'select',opciones:['Biosanitario','Cortopunzante','Anatomopatológico','Químico','Ordinario']},
    {etiqueta:'Cantidad (kg)',tipo:'numero'},
    {etiqueta:'¿Segregación correcta en la fuente?',tipo:'si_no'},{etiqueta:'¿Rotulado conforme a la norma?',tipo:'si_no'},
    {etiqueta:'Responsable de recolección',tipo:'texto'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'control_medicamentos',vertical:'salud',nombre:'Control de Medicamentos de Control Especial',
   keywords:['medicamentos','control especial','psicotropico','estupefaciente','custodia','farmacia','kardex'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Medicamento',tipo:'texto'},{etiqueta:'Lote',tipo:'texto'},
    {etiqueta:'Cantidad en existencia',tipo:'numero'},{etiqueta:'Cantidad dispensada',tipo:'numero'},
    {etiqueta:'Paciente / Servicio destino',tipo:'texto'},{etiqueta:'Responsable de farmacia',tipo:'texto'},
    {etiqueta:'Firma de quien dispensa',tipo:'firma'},{etiqueta:'Firma de quien recibe',tipo:'firma'},
  ]},

  {id:'inspeccion_habilitacion',vertical:'salud',nombre:'Lista de Verificación de Habilitación de Servicios de Salud',
   keywords:['habilitacion','estandares','infraestructura','dotacion','autoevaluacion','servicio de salud','calidad'],
   campos_clave:[
    {etiqueta:'Servicio evaluado',tipo:'texto'},{etiqueta:'Fecha de autoevaluación',tipo:'fecha_auto'},
    {etiqueta:'Estándar de infraestructura',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Estándar de dotación',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Estándar de procesos prioritarios',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Estándar de historia clínica',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Hallazgos',tipo:'textarea'},{etiqueta:'Plan de mejoramiento',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'reporte_evento_adverso',vertical:'salud',nombre:'Reporte de Evento Adverso / Seguridad del Paciente',
   keywords:['evento adverso','seguridad del paciente','incidente','near miss','analisis causa raiz','centinela'],
   campos_clave:[
    {etiqueta:'Fecha del evento',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Servicio',tipo:'select',opciones:['Urgencias','Hospitalización','Cirugía','UCI','Consulta externa','Otro']},
    {etiqueta:'Tipo de evento',tipo:'select',opciones:['Evento adverso','Incidente (near miss)','Evento centinela']},
    {etiqueta:'Descripción del evento',tipo:'textarea'},{etiqueta:'¿Se notificó a la familia?',tipo:'si_no'},
    {etiqueta:'Acción inmediata tomada',tipo:'textarea'},{etiqueta:'Responsable del análisis',tipo:'texto'},
    {etiqueta:'Firma',tipo:'firma'},
  ]},
];
