// Catálogo compartido de plantillas — consumido por digitalizador.html (sugerencias matchTemplate) y plantillas.html (índice navegable)
// Contexto de localización del núcleo SST — el MISMO formulario sirve en los 4
// países; solo cambia el ente, el comité y la cita legal (verificado ago-2026).
// `comite_de` es el nombre del comité con su artículo/contracción correctos
// ("del COPASST", "de la Comisión…"), para que los campos localizados
// ("Presidente {comite_de}") queden gramaticalmente bien en cada país.
const SST_LOCAL = {
  co: { pais:'Colombia',    regulador:'Ministerio del Trabajo',              comite:'COPASST',                                  comite_de:'del COPASST',                                comite_sigla:'COPASST', norma:'Decreto 1072/2015 · Res. 0312/2019',                  umbral:'—' },
  pa: { pais:'Panamá',      regulador:'CSS · MITRADEL',                      comite:'Comité de Salud, Seguridad e Higiene',     comite_de:'del Comité de Salud, Seguridad e Higiene',   comite_sigla:'CSSH',     norma:'Reglamento de Riesgos Profesionales (Res. 45.588, CSS)', umbral:'según la empresa' },
  cr: { pais:'Costa Rica',  regulador:'MTSS · Consejo de Salud Ocupacional', comite:'Comisión de Salud Ocupacional',            comite_de:'de la Comisión de Salud Ocupacional',        comite_sigla:'CSO',      norma:'Ley 6727 · Reglamento de Seguridad e Higiene',        umbral:'10+ trabajadores' },
  sv: { pais:'El Salvador', regulador:'MTPS',                                comite:'Comité de Seguridad y Salud Ocupacional',  comite_de:'del Comité de Seguridad y Salud Ocupacional', comite_sigla:'CSSO',    norma:'Ley 254/2010 · Reglamentos Dec. 86 y 89 de 2012',     umbral:'15+ trabajadores' },
};

// Localización de texto por país. Las plantillas del núcleo escriben el comité
// con tokens ({comite}, {comite_de}, {comite_sigla}); aquí se sustituyen por el
// nombre vigente en el país de la organización. La sustitución ocurre una sola
// vez —al precargar la plantilla en el Digitalizador— y el formulario se guarda
// ya localizado, así que en Panamá "Acta de Reunión — COPASST" nace como
// "Acta de Reunión — Comité de Salud, Seguridad e Higiene".
function skfLocalizeText(str, paisCode) {
  if (!str || str.indexOf('{') === -1) return str;
  const L = SST_LOCAL[paisCode] || SST_LOCAL.co;
  return str
    .replace(/\{comite_sigla\}/g, L.comite_sigla)
    .replace(/\{comite_de\}/g, L.comite_de)
    .replace(/\{comite\}/g, L.comite);
}

// Devuelve una COPIA de la plantilla con norma, nombre y etiquetas de campo ya
// localizados al país. No muta el original del catálogo.
function skfLocalizeTemplate(tmpl, paisCode) {
  if (!tmpl) return tmpl;
  const out = Object.assign({}, tmpl);
  const L = tmpl.localizacion && (tmpl.localizacion[paisCode] || tmpl.localizacion.co);
  if (L && L.norma) out.norma = L.norma;
  out.nombre = skfLocalizeText(tmpl.nombre, paisCode);
  if (Array.isArray(tmpl.campos_clave)) {
    out.campos_clave = tmpl.campos_clave.map(c =>
      Object.assign({}, c, { etiqueta: skfLocalizeText(c.etiqueta, paisCode) }));
  }
  return out;
}

const FORM_LIBRARY = [
  // ── Calidad / SGC Verticales (ISO 9001:2015) ──────────────────
  {id:'auditoria_interna_iso',vertical:'calidad',nombre:'Checklist de Auditoría Interna (ISO 9001 — Cl. 9.2)',norma:'ISO 9001:2015 — Cl. 9.2',
   keywords:['auditoria interna','iso 9001','no conformidad','hallazgo de auditoria','criterio de auditoria','plan de auditoria','evidencia objetiva','auditor lider'],
   campos_clave:[
    {etiqueta:'Proceso / área auditada',tipo:'texto'},{etiqueta:'Fecha de auditoría',tipo:'fecha_auto'},
    {etiqueta:'Auditor líder',tipo:'texto'},{etiqueta:'Norma / criterio de auditoría',tipo:'texto'},
    {etiqueta:'Requisito verificado',tipo:'textarea'},{etiqueta:'Evidencia objetiva',tipo:'textarea'},
    {etiqueta:'Resultado',tipo:'select',opciones:['Conforme','No conformidad mayor','No conformidad menor','Observación']},
    {etiqueta:'Hallazgo',tipo:'textarea'},{etiqueta:'Responsable del proceso',tipo:'texto'},
    {etiqueta:'Fecha de seguimiento',tipo:'fecha'},{etiqueta:'Firma del auditor',tipo:'firma'},
    {etiqueta:'Firma del auditado',tipo:'firma'},
  ]},
  {id:'no_conformidad_iso',vertical:'calidad',nombre:'Informe de No Conformidad (ISO 9001 — Cl. 8.7/10.2)',norma:'ISO 9001:2015 — Cl. 8.7 / 10.2',
   keywords:['no conformidad','salida no conforme','correccion inmediata','causa raiz','clasificacion mayor menor','contencion'],
   campos_clave:[
    {etiqueta:'Número de no conformidad',tipo:'numero'},{etiqueta:'Fecha de detección',tipo:'fecha_auto'},
    {etiqueta:'Fuente',tipo:'select',opciones:['Auditoría interna','Auditoría externa','Queja de cliente','Proceso interno','Producto no conforme']},
    {etiqueta:'Descripción de la no conformidad',tipo:'textarea'},{etiqueta:'Requisito incumplido',tipo:'texto'},
    {etiqueta:'Evidencia',tipo:'foto'},
    {etiqueta:'Clasificación',tipo:'select',opciones:['Mayor','Menor']},
    {etiqueta:'Corrección inmediata / contención',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha límite de cierre',tipo:'fecha'},
    {etiqueta:'Firma del responsable de calidad',tipo:'firma'},
  ]},
  {id:'capa_iso',vertical:'calidad',nombre:'Plan de Acción Correctiva y Preventiva — CAPA (ISO 9001 — Cl. 10.2)',norma:'ISO 9001:2015 — Cl. 10.2',
   keywords:['accion correctiva','accion preventiva','capa','causa raiz','5 porques','ishikawa','verificacion de eficacia','plan de accion'],
   campos_clave:[
    {etiqueta:'Número de CAPA',tipo:'numero'},{etiqueta:'Origen / NC asociada',tipo:'texto'},
    {etiqueta:'Fecha de apertura',tipo:'fecha_auto'},{etiqueta:'Análisis de causa raíz',tipo:'textarea'},
    {etiqueta:'Acción correctiva propuesta',tipo:'textarea'},{etiqueta:'Responsable de la implementación',tipo:'texto'},
    {etiqueta:'Fecha límite de implementación',tipo:'fecha'},{etiqueta:'¿Implementación verificada?',tipo:'si_no'},
    {etiqueta:'Verificación de eficacia',tipo:'textarea'},{etiqueta:'Fecha de cierre',tipo:'fecha'},
    {etiqueta:'Firma del responsable de calidad',tipo:'firma'},
  ]},
  {id:'listado_maestro_documentos',vertical:'calidad',nombre:'Listado Maestro de Documentos (ISO 9001 — Cl. 7.5)',
   keywords:['listado maestro','control documental','version','documento controlado','codigo de documento','vigente','obsoleto'],
   campos_clave:[
    {etiqueta:'Código del documento',tipo:'texto'},{etiqueta:'Nombre del documento',tipo:'texto'},
    {etiqueta:'Tipo',tipo:'select',opciones:['Procedimiento','Instructivo','Formato','Manual','Política','Documento externo']},
    {etiqueta:'Versión',tipo:'texto'},{etiqueta:'Fecha de emisión',tipo:'fecha'},
    {etiqueta:'Próxima revisión',tipo:'fecha'},{etiqueta:'Elaborado por',tipo:'texto'},
    {etiqueta:'Aprobado por',tipo:'texto'},
    {etiqueta:'Estado',tipo:'select',opciones:['Vigente','Obsoleto','En revisión']},
    {etiqueta:'Ubicación / repositorio',tipo:'texto'},
  ]},
  {id:'revision_direccion',vertical:'calidad',nombre:'Acta de Revisión por la Dirección (ISO 9001 — Cl. 9.3)',
   keywords:['revision por la direccion','alta direccion','entradas','salidas','desempeno del sgc','oportunidades de mejora'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Asistentes',tipo:'textarea'},
    {etiqueta:'Estado de acciones de revisiones previas',tipo:'textarea'},
    {etiqueta:'Desempeño y eficacia del SGC',tipo:'textarea'},{etiqueta:'Resultados de auditorías',tipo:'textarea'},
    {etiqueta:'Satisfacción del cliente',tipo:'textarea'},
    {etiqueta:'No conformidades y acciones correctivas',tipo:'textarea'},
    {etiqueta:'Desempeño de proveedores externos',tipo:'textarea'},
    {etiqueta:'Adecuación de recursos',tipo:'textarea'},{etiqueta:'Riesgos y oportunidades',tipo:'textarea'},
    {etiqueta:'Decisiones y acciones',tipo:'textarea'},{etiqueta:'Necesidad de cambios en el SGC',tipo:'textarea'},
    {etiqueta:'Firma del representante de la dirección',tipo:'firma'},
  ]},
  {id:'indicador_kpi',vertical:'calidad',nombre:'Ficha de Indicador de Gestión / KPI (ISO 9001 — Cl. 9.1, 6.2)',
   keywords:['indicador','kpi','meta','formula','frecuencia de medicion','tendencia','semaforo'],
   campos_clave:[
    {etiqueta:'Nombre del indicador',tipo:'texto'},{etiqueta:'Proceso / objetivo asociado',tipo:'texto'},
    {etiqueta:'Fórmula de cálculo',tipo:'texto'},{etiqueta:'Fuente de datos',tipo:'texto'},
    {etiqueta:'Responsable',tipo:'texto'},
    {etiqueta:'Frecuencia de medición',tipo:'select',opciones:['Diaria','Semanal','Mensual','Trimestral','Anual']},
    {etiqueta:'Meta',tipo:'numero'},{etiqueta:'Resultado del periodo',tipo:'numero'},
    {etiqueta:'Semáforo',tipo:'select',opciones:['Verde - Cumple','Amarillo - En riesgo','Rojo - No cumple']},
    {etiqueta:'Acciones de mejora asociadas',tipo:'textarea'},
  ]},
  {id:'evaluacion_proveedores_iso',vertical:'calidad',nombre:'Evaluación y Reevaluación de Proveedores (ISO 9001 — Cl. 8.4)',
   keywords:['evaluacion de proveedores','reevaluacion','criterios de seleccion','desempeno del proveedor','calificacion del proveedor'],
   campos_clave:[
    {etiqueta:'Nombre del proveedor',tipo:'texto'},{etiqueta:'NIT',tipo:'texto'},
    {etiqueta:'Categoría / criticidad',tipo:'select',opciones:['Crítico','No crítico']},
    {etiqueta:'Calidad del producto/servicio',tipo:'radio',opciones:['1','2','3','4','5']},
    {etiqueta:'Cumplimiento de tiempos de entrega',tipo:'radio',opciones:['1','2','3','4','5']},
    {etiqueta:'Cumplimiento de precio acordado',tipo:'radio',opciones:['1','2','3','4','5']},
    {etiqueta:'¿Certificaciones vigentes?',tipo:'si_no'},{etiqueta:'Calificación total',tipo:'numero'},
    {etiqueta:'Resultado',tipo:'select',opciones:['Aprobado','Aprobado con condiciones','Rechazado']},
    {etiqueta:'Acciones de seguimiento',tipo:'textarea'},{etiqueta:'Próxima reevaluación',tipo:'fecha'},
    {etiqueta:'Firma del evaluador',tipo:'firma'},
  ]},
  {id:'encuesta_satisfaccion',vertical:'calidad',nombre:'Encuesta de Satisfacción al Cliente (ISO 9001 — Cl. 9.1.2)',
   keywords:['satisfaccion','encuesta','opinion','calidad del servicio','recomendaria','atencion','experiencia','califique'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Servicio / Producto evaluado',tipo:'texto'},
    {etiqueta:'Calificación general',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'¿Recomendaría nuestro servicio?',tipo:'si_no'},
    {etiqueta:'Aspectos positivos',tipo:'textarea'},{etiqueta:'Aspectos a mejorar',tipo:'textarea'},
    {etiqueta:'Nombre del cliente (opcional)',tipo:'texto'},{etiqueta:'Correo (opcional)',tipo:'email'},
  ]},

  // ── SST Verticales (Decreto 1072/2015 · Res. 0312/2019 · GTC 45 · Res. 1401/2007) ──
  {id:'inspeccion_sst',vertical:'sst',nucleo:true,freq:1,localizacion:SST_LOCAL,nombre:'Lista de Verificación SST',
   keywords:['inspeccion','verificacion','sst','seguridad','salud','trabajo','cumple','riesgo','epp','hallazgo'],
   campos_clave:[
    {etiqueta:'Empresa / Establecimiento',tipo:'texto'},{etiqueta:'Fecha de inspección',tipo:'fecha_auto'},
    {etiqueta:'Área inspeccionada',tipo:'select',opciones:['Producción','Almacén','Oficinas','Mantenimiento','Otro']},
    {etiqueta:'Inspector responsable',tipo:'texto'},
    {etiqueta:'Calificación',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'Observaciones / Hallazgos',tipo:'textarea'},{etiqueta:'Acción correctiva',tipo:'textarea'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Firma del inspector',tipo:'firma'},
    {etiqueta:'Ubicación GPS',tipo:'ubicacion'},
  ]},
  {id:'asistencia',vertical:'sst',nucleo:true,freq:6,localizacion:SST_LOCAL,nombre:'Registro de Asistencia a Capacitación',
   keywords:['asistencia','capacitacion','participante','instructor','facilitador','tema','objetivo'],
   campos_clave:[
    {etiqueta:'Nombre completo del participante',tipo:'texto'},
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora de inicio',tipo:'hora_auto'},
    {etiqueta:'Hora de finalización',tipo:'hora'},
    {etiqueta:'Facilitador / Instructor',tipo:'texto'},
    {etiqueta:'Cargo',tipo:'select',opciones:['Operario','Técnico','Profesional','Supervisor','Coordinador','Otro']},
    {etiqueta:'Firma del participante',tipo:'firma'},
    {etiqueta:'¿Completó la capacitación?',tipo:'si_no'},
  ]},
  {id:'matriz_peligros',vertical:'sst',nucleo:true,freq:13,localizacion:SST_LOCAL,nombre:'Matriz de Identificación de Peligros y Valoración de Riesgos (GTC-45)',norma:'GTC 45 · Decreto 1072/2015',
   keywords:['matriz','peligro','riesgo','gtc','valoracion','control','consecuencia','probabilidad','nivel de riesgo','intervencion'],
   campos_clave:[
    {etiqueta:'Proceso / Actividad',tipo:'texto'},{etiqueta:'Área / Lugar',tipo:'select',opciones:['Producción','Almacén','Oficinas','Mantenimiento','Exteriores','Otro']},
    {etiqueta:'Tipo de peligro',tipo:'select',opciones:['Físico','Químico','Biológico','Biomecánico','Psicosocial','Condiciones de seguridad','Fenómenos naturales']},
    {etiqueta:'Fuente del peligro',tipo:'texto'},{etiqueta:'Descripción del peligro',tipo:'textarea'},
    {etiqueta:'Efectos posibles',tipo:'textarea'},
    {etiqueta:'Nivel de deficiencia',tipo:'radio',opciones:['MA - Muy alto (10)','A - Alto (6)','M - Medio (2)','B - Bajo (0)']},
    {etiqueta:'Nivel de exposición',tipo:'radio',opciones:['EC - Continua (4)','EF - Frecuente (3)','EO - Ocasional (2)','EE - Esporádica (1)']},
    {etiqueta:'Nivel de consecuencia',tipo:'radio',opciones:['Catastrófico (100)','Muy grave (60)','Grave (25)','Leve (10)']},
    {etiqueta:'¿Existen controles actuales?',tipo:'si_no'},{etiqueta:'Medidas de intervención',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha de ejecución',tipo:'fecha_auto'},
    {etiqueta:'Ubicación GPS',tipo:'ubicacion'},{etiqueta:'Fotografía del riesgo',tipo:'foto'},
  ]},

  {id:'permiso_trabajo',vertical:'sst',nucleo:true,freq:4,localizacion:SST_LOCAL,nombre:'Permiso de Trabajo de Alto Riesgo',
   keywords:['permiso','altura','espacio confinado','electrico','caliente','riesgo','ats','atp','trabajador','petar','resolucion 4272','resolucion 0491'],
   campos_clave:[
    {etiqueta:'Número de permiso',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Hora de finalización',tipo:'hora'},
    {etiqueta:'Tipo de trabajo',tipo:'select',opciones:['Trabajo en altura','Espacio confinado','Trabajo en caliente','Trabajo eléctrico','Otro']},
    {etiqueta:'Descripción del trabajo',tipo:'textarea'},
    {etiqueta:'¿Se realizó análisis de riesgos?',tipo:'si_no'},
    {etiqueta:'EPP requerido',tipo:'checkbox_multi',opciones:['Casco','Guantes','Arnés','Gafas','Botas','Tapabocas']},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del supervisor',tipo:'firma'},
  ]},

  {id:'incidente_accidente',vertical:'sst',nucleo:true,freq:7,localizacion:SST_LOCAL,nombre:'Reporte de Incidente / Accidente Laboral',
   keywords:['incidente','accidente','lesion','trabajador','causa','testigo','investigacion','herido','medica'],
   campos_clave:[
    {etiqueta:'Fecha del incidente',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Trabajador involucrado',tipo:'texto'},{etiqueta:'Cargo',tipo:'select'},
    {etiqueta:'Tipo de evento',tipo:'select',opciones:['Incidente','Accidente de trabajo','Enfermedad laboral','Casi accidente']},
    {etiqueta:'Descripción del evento',tipo:'textarea'},{etiqueta:'Causa raíz',tipo:'textarea'},
    {etiqueta:'¿Hubo atención médica?',tipo:'si_no'},{etiqueta:'Días de incapacidad',tipo:'numero'},
    {etiqueta:'Fotografía de la escena',tipo:'foto'},{etiqueta:'Ubicación GPS del incidente',tipo:'ubicacion'},
    {etiqueta:'Firma del jefe inmediato',tipo:'firma'},
  ]},

  {id:'autoevaluacion_res0312',vertical:'sst',nucleo:true,freq:14,localizacion:SST_LOCAL,nombre:'Autoevaluación de Estándares Mínimos SG-SST (Res. 0312/2019)',norma:'Resolución 0312 de 2019',
   keywords:['estandares minimos','resolucion 0312','autoevaluacion','sgsst','plan de mejora','calificacion del sistema'],
   campos_clave:[
    {etiqueta:'Fecha de autoevaluación',tipo:'fecha_auto'},{etiqueta:'Número de trabajadores',tipo:'numero'},
    {etiqueta:'Nivel de riesgo de la empresa',tipo:'select',opciones:['I','II','III','IV','V']},
    {etiqueta:'Capítulo aplicable',tipo:'select',opciones:['Cap. 1 - 7 estándares (1-10 trab.)','Cap. 2 - estándares intermedios (11-50 trab.)','Cap. 3 - 60 estándares (>50 trab. o riesgo IV-V)']},
    {etiqueta:'Estándar evaluado',tipo:'texto'},{etiqueta:'¿Cumple?',tipo:'si_no'},
    {etiqueta:'Calificación (%)',tipo:'numero'},{etiqueta:'Plan de mejora / acción',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma del responsable SST',tipo:'firma'},
  ]},

  {id:'reporte_condicion_acto_inseguro',vertical:'sst',nucleo:true,freq:2,localizacion:SST_LOCAL,nombre:'Reporte de Acto y Condición Insegura',
   keywords:['acto inseguro','condicion insegura','autorreporte','reporte de peligro','casi accidente','condiciones de trabajo'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Reportado por',tipo:'texto'},
    {etiqueta:'Área',tipo:'select',opciones:['Producción','Almacén','Oficinas','Mantenimiento','Otro']},
    {etiqueta:'Clasificación',tipo:'select',opciones:['Acto inseguro','Condición insegura']},
    {etiqueta:'Nivel de riesgo',tipo:'select',opciones:['Alto','Medio','Bajo']},
    {etiqueta:'Descripción',tipo:'textarea'},{etiqueta:'Control propuesto',tipo:'textarea'},
    {etiqueta:'Plazo de corrección',tipo:'select',opciones:['Inmediato','Corto plazo','Mediano plazo']},
    {etiqueta:'Fotografía',tipo:'foto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'simulacro_evacuacion',vertical:'sst',nucleo:true,freq:11,localizacion:SST_LOCAL,nombre:'Evaluación de Simulacro de Evacuación',
   keywords:['simulacro','evacuacion','punto de encuentro','brigada','tiempo de evacuacion','conteo de personal'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora de inicio',tipo:'hora_auto'},
    {etiqueta:'Objetivo del simulacro',tipo:'texto'},{etiqueta:'Número de participantes',tipo:'numero'},
    {etiqueta:'Tiempo de activación de la alarma',tipo:'texto'},{etiqueta:'Tiempo de evacuación total',tipo:'texto'},
    {etiqueta:'¿Llegada al punto de encuentro completa?',tipo:'si_no'},
    {etiqueta:'Comportamiento durante la evacuación',tipo:'select',opciones:['Adecuado','Con observaciones','Deficiente']},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Fotografía',tipo:'foto'},
    {etiqueta:'Firma del coordinador de brigada',tipo:'firma'},
  ]},

  {id:'acta_copasst',vertical:'sst',nucleo:true,freq:9,localizacion:SST_LOCAL,nombre:'Acta de Reunión — {comite}',
   keywords:['copasst','copasos','comite paritario','comite de salud','comision de salud ocupacional','representante empleador','representante trabajadores','presidente copasst','secretario copasst','sgsst','sso'],
   campos_clave:[
    {etiqueta:'Número de acta',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Hora de finalización',tipo:'hora'},
    {etiqueta:'Tipo de reunión',tipo:'select',opciones:['Ordinaria mensual','Extraordinaria']},
    {etiqueta:'Presidente {comite_de}',tipo:'texto'},{etiqueta:'Secretario {comite_de}',tipo:'texto'},
    {etiqueta:'Representante del empleador',tipo:'texto'},{etiqueta:'Representante de los trabajadores',tipo:'texto'},
    {etiqueta:'Orden del día',tipo:'textarea'},{etiqueta:'Temas tratados y decisiones',tipo:'textarea'},
    {etiqueta:'Compromisos / Responsables',tipo:'textarea'},{etiqueta:'Fecha de seguimiento',tipo:'fecha_auto'},
    {etiqueta:'Firma del presidente',tipo:'firma'},{etiqueta:'Firma del secretario',tipo:'firma'},
  ]},

  {id:'entrega_epp',vertical:'sst',nucleo:true,freq:5,localizacion:SST_LOCAL,nombre:'Entrega de Elementos de Protección Personal (EPP)',
   keywords:['epp','elementos de proteccion personal','dotacion','casco','botas de seguridad','arnés','proteccion personal','kit epp','recibido conforme','entrega dotacion'],
   campos_clave:[
    {etiqueta:'Fecha de entrega',tipo:'fecha_auto'},{etiqueta:'Nombre del trabajador',tipo:'texto'},
    {etiqueta:'Cargo',tipo:'select',opciones:['Operario','Técnico','Supervisor','Coordinador','Inspector','Otro']},
    {etiqueta:'Área',tipo:'select',opciones:['Producción','Almacén','Mantenimiento','Obra','Laboratorio','Otro']},
    {etiqueta:'Elemento de protección entregado',tipo:'select',opciones:['Casco','Guantes de vaqueta','Guantes de nitrilo','Botas de seguridad','Gafas de seguridad','Protección auditiva','Tapabocas','Arnés','Overol','Otro']},
    {etiqueta:'Talla / Referencia',tipo:'texto'},{etiqueta:'Cantidad',tipo:'numero'},
    {etiqueta:'Motivo de entrega',tipo:'select',opciones:['Primera entrega','Reposición por desgaste','Reposición por pérdida','Cambio de cargo']},
    {etiqueta:'Fecha de vencimiento del EPP',tipo:'fecha'},
    {etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma del trabajador (recibí conforme)',tipo:'firma'},
    {etiqueta:'Firma del responsable de entrega',tipo:'firma'},
  ]},

  {id:'investigacion_at',vertical:'sst',nucleo:true,freq:8,localizacion:SST_LOCAL,nombre:'Investigación de Accidente de Trabajo (Res. 1401/2007)',norma:'Resolución 1401 de 2007',
   keywords:['causas basicas','causas inmediatas','accion correctiva','plan de accion','factores contribuyentes','causas raiz','resolucion 1401','investigacion de accidente'],
   campos_clave:[
    {etiqueta:'Fecha del accidente',tipo:'fecha_auto'},{etiqueta:'Hora del accidente',tipo:'hora_auto'},
    {etiqueta:'Fecha de investigación',tipo:'fecha_auto'},{etiqueta:'Trabajador accidentado',tipo:'texto'},
    {etiqueta:'Cargo',tipo:'select'},{etiqueta:'ARL',tipo:'select',opciones:['Positiva','Sura','Colmena','Axa Colpatria','Bolívar','Liberty','Otro']},
    {etiqueta:'Días de incapacidad',tipo:'numero'},
    {etiqueta:'Descripción detallada del accidente',tipo:'textarea'},
    {etiqueta:'Causas inmediatas — actos inseguros',tipo:'textarea'},
    {etiqueta:'Causas inmediatas — condiciones inseguras',tipo:'textarea'},
    {etiqueta:'Causas básicas — factores personales',tipo:'textarea'},
    {etiqueta:'Causas básicas — factores del trabajo',tipo:'textarea'},
    {etiqueta:'Plan de acción correctiva',tipo:'textarea'},{etiqueta:'Responsable del plan',tipo:'texto'},
    {etiqueta:'Fecha límite de acción',tipo:'fecha_auto'},{etiqueta:'¿Se reportó a la ARL?',tipo:'si_no'},
    {etiqueta:'Fotografía de la escena',tipo:'foto'},{etiqueta:'Ubicación GPS',tipo:'ubicacion'},
    {etiqueta:'Firma del investigador',tipo:'firma'},{etiqueta:'Firma del representante legal',tipo:'firma'},
  ]},

  {id:'inspeccion_botiquin',vertical:'sst',nucleo:true,freq:10,localizacion:SST_LOCAL,nombre:'Inspección de Botiquín y Brigada de Emergencias',
   keywords:['botiquin','brigada','emergencia','extintor','primeros auxilios','camilla','kit de emergencia','evacuacion','punto de encuentro'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Área / Ubicación',tipo:'texto'},
    {etiqueta:'Inspector',tipo:'texto'},
    {etiqueta:'¿Botiquín visible y accesible?',tipo:'si_no'},
    {etiqueta:'¿Analgésicos disponibles?',tipo:'si_no'},{etiqueta:'¿Vendas y gasas?',tipo:'si_no'},
    {etiqueta:'¿Antisépticos (alcohol, agua oxigenada)?',tipo:'si_no'},
    {etiqueta:'¿Guantes desechables?',tipo:'si_no'},{etiqueta:'¿Extintor cercano y vigente?',tipo:'si_no'},
    {etiqueta:'Fecha de vencimiento del elemento más próximo a vencer',tipo:'fecha'},
    {etiqueta:'Elementos faltantes o vencidos',tipo:'textarea'},
    {etiqueta:'Observaciones generales',tipo:'textarea'},
    {etiqueta:'Fotografía del botiquín',tipo:'foto'},
    {etiqueta:'Firma del inspector',tipo:'firma'},
  ]},

  {id:'examen_medico_sst',vertical:'sst',nucleo:true,freq:12,localizacion:SST_LOCAL,nombre:'Remisión / Resultado de Examen Médico Ocupacional',
   keywords:['examen medico','medico ocupacional','profesiograma','aptitud','ingreso','periodico','retiro','apto','restriccion','eps'],
   campos_clave:[
    {etiqueta:'Nombre del trabajador',tipo:'texto'},{etiqueta:'Número de cédula',tipo:'numero'},
    {etiqueta:'Cargo',tipo:'select'},{etiqueta:'Área',tipo:'select'},
    {etiqueta:'Tipo de examen',tipo:'select',opciones:['Ingreso','Periódico','Retiro','Post-incapacidad','Reubicación laboral','Cambio de cargo']},
    {etiqueta:'Fecha de remisión',tipo:'fecha_auto'},{etiqueta:'IPS / Médico ocupacional',tipo:'texto'},
    {etiqueta:'Resultado',tipo:'select',opciones:['Apto','Apto con restricciones','No apto temporalmente','No apto permanentemente']},
    {etiqueta:'Restricciones / Recomendaciones médicas',tipo:'textarea'},
    {etiqueta:'Fecha del próximo examen',tipo:'fecha'},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del responsable SST',tipo:'firma'},
  ]},

  {id:'toma_5',vertical:'sst',nucleo:true,freq:3,localizacion:SST_LOCAL,nombre:'Toma 5 - Análisis Pre-Tarea de Trabajo de Alto Riesgo',
   keywords:['toma 5','toma cinco','take five','pre tarea','pretarea','analisis de riesgo','altura','espacio confinado','trabajo en caliente','chispa','autorizacion de trabajo','permiso','checklist de seguridad'],
   campos_clave:[
    {etiqueta:'Área / lugar de trabajo',tipo:'texto'},{etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Trabajador que ejecuta la tarea',tipo:'texto'},
    {etiqueta:'Tipo de trabajo de alto riesgo',tipo:'select',opciones:['Trabajo en altura','Espacio confinado','Trabajo en caliente (chispa)','Trabajo eléctrico','Excavación','Izaje de cargas','Otro']},
    {etiqueta:'PASO 1 — PARA: detente y piensa antes de actuar',tipo:'separador'},
    {etiqueta:'¿Te detuviste a pensar en los riesgos de esta tarea antes de iniciar?',tipo:'si_no'},
    {etiqueta:'PASO 2 — PIENSA: identifica los peligros',tipo:'separador'},
    {etiqueta:'Peligros identificados',tipo:'checkbox_multi',opciones:['Caída de altura','Atmósfera peligrosa / espacio confinado','Energía eléctrica','Sustancias químicas','Maquinaria o equipos en movimiento','Chispa / fuente de ignición','Otro']},
    {etiqueta:'PASO 3 — OBSERVA: verifica las condiciones del entorno',tipo:'separador'},
    {etiqueta:'¿Se verificaron las condiciones del entorno antes de iniciar?',tipo:'si_no'},
    {etiqueta:'Observaciones del entorno',tipo:'textarea'},
    {etiqueta:'PASO 4 — EVALÚA Y DECIDE: define los controles necesarios',tipo:'separador'},
    {etiqueta:'Controles y EPP requeridos',tipo:'checkbox_multi',opciones:['Arnés y línea de vida','Detector de gases','Permiso de trabajo en caliente','Bloqueo y etiquetado (LOTO)','Ventilación / extracción','Extintor disponible','Vigía / supervisor asignado']},
    {etiqueta:'¿Cuenta con el permiso de trabajo correspondiente?',tipo:'si_no'},
    {etiqueta:'PASO 5 — ACTÚA: autorización final',tipo:'separador'},
    {etiqueta:'¿Autorizado para iniciar el trabajo?',tipo:'si_no'},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del supervisor que autoriza',tipo:'firma'},
  ]},

  // ── Inmuebles / NFPA Verticales (seguridad contra incendios y facilidades) ──
  {id:'inspeccion_extintores',vertical:'inmuebles',nombre:'Inspección de Extintores (NFPA 10)',norma:'NFPA 10',
   keywords:['extintor','extintores','nfpa 10','recarga','presion extintor','sello de seguridad'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Ubicación del extintor',tipo:'texto'},
    {etiqueta:'Tipo de extintor',tipo:'select',opciones:['ABC','CO2','Agente limpio','Agua','Espuma']},
    {etiqueta:'¿Presión en rango correcto?',tipo:'si_no'},{etiqueta:'¿Sello de seguridad intacto?',tipo:'si_no'},
    {etiqueta:'¿Señalización y acceso despejado?',tipo:'si_no'},{etiqueta:'¿Sin daños visibles en manguera o cilindro?',tipo:'si_no'},
    {etiqueta:'Fecha de próxima recarga / vencimiento',tipo:'fecha'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_bomba_incendio',vertical:'inmuebles',nombre:'Inspección de Bomba Contra Incendio (NFPA 20/25)',norma:'NFPA 20 / 25',
   keywords:['bomba contra incendio','nfpa 20','nfpa 25','presion de succion','presion de descarga','jockey pump'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Identificación de la bomba',tipo:'texto'},
    {etiqueta:'Presión de succión (PSI)',tipo:'numero'},{etiqueta:'Presión de descarga (PSI)',tipo:'numero'},
    {etiqueta:'¿Arranque automático correcto?',tipo:'si_no'},{etiqueta:'¿Bomba jockey opera correctamente?',tipo:'si_no'},
    {etiqueta:'¿Sin fugas visibles?',tipo:'si_no'},{etiqueta:'¿Nivel de combustible/batería adecuado (si aplica)?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_rociadores',vertical:'inmuebles',nombre:'Inspección de Sistema de Rociadores Automáticos (NFPA 13)',norma:'NFPA 13 / 25',
   keywords:['rociadores','sprinklers','nfpa 13','valvula de control','red humeda','red seca'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Área / Zona evaluada',tipo:'texto'},
    {etiqueta:'¿Válvulas de control abiertas y selladas?',tipo:'si_no'},{etiqueta:'¿Rociadores sin obstrucción ni daño visible?',tipo:'si_no'},
    {etiqueta:'Presión del sistema (PSI)',tipo:'numero'},{etiqueta:'¿Manómetros en rango correcto?',tipo:'si_no'},
    {etiqueta:'¿Sin fugas visibles en tuberías?',tipo:'si_no'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_alarma_incendio',vertical:'inmuebles',nombre:'Inspección de Sistema de Detección y Alarma de Incendio (NFPA 72)',norma:'NFPA 72',
   keywords:['alarma de incendio','deteccion','nfpa 72','sensor de humo','panel de alarma','estacion manual'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Zona / Área evaluada',tipo:'texto'},
    {etiqueta:'¿Panel de alarma sin fallas reportadas?',tipo:'si_no'},{etiqueta:'¿Detectores de humo sin obstrucción?',tipo:'si_no'},
    {etiqueta:'¿Estaciones manuales accesibles?',tipo:'si_no'},{etiqueta:'¿Sirenas y luces estroboscópicas funcionan?',tipo:'si_no'},
    {etiqueta:'¿Batería de respaldo en buen estado?',tipo:'si_no'},{etiqueta:'Hallazgos',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_salidas_emergencia',vertical:'inmuebles',nombre:'Inspección de Salidas de Emergencia y Señalización (NFPA 101)',norma:'NFPA 101',
   keywords:['salida de emergencia','nfpa 101','senalizacion','ruta de evacuacion','iluminacion de emergencia','medios de egreso'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Ubicación / piso',tipo:'texto'},
    {etiqueta:'¿Salida libre de obstrucciones?',tipo:'si_no'},{etiqueta:'¿Puerta abre en sentido de evacuación?',tipo:'si_no'},
    {etiqueta:'¿Señalización de salida iluminada y visible?',tipo:'si_no'},
    {etiqueta:'¿Ruta de evacuación despejada y señalizada?',tipo:'si_no'},
    {etiqueta:'¿Luz de emergencia funcional (prueba 30 seg)?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Foto',tipo:'foto'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_cuarto_electrico',vertical:'inmuebles',nombre:'Inspección de Cuarto Eléctrico y Tableros (NFPA 70E)',
   keywords:['cuarto electrico','tablero','breaker','cortocircuito','arc flash','nfpa 70e','subestacion'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Ubicación / Tablero',tipo:'texto'},
    {etiqueta:'¿Señalización de riesgo eléctrico visible?',tipo:'si_no'},{etiqueta:'¿Acceso libre y despejado?',tipo:'si_no'},
    {etiqueta:'¿Tablero rotulado correctamente?',tipo:'si_no'},{etiqueta:'¿Sin signos de sobrecalentamiento u olor a quemado?',tipo:'si_no'},
    {etiqueta:'¿Breakers en buen estado?',tipo:'si_no'},{etiqueta:'¿Conexiones a tierra correctas?',tipo:'si_no'},
    {etiqueta:'¿Extintor cercano disponible?',tipo:'si_no'},{etiqueta:'Hallazgos',tipo:'textarea'},
    {etiqueta:'Foto',tipo:'foto'},{etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_gabinetes_mangueras',vertical:'inmuebles',nombre:'Inspección de Gabinetes y Mangueras Contra Incendio (NFPA 14)',
   keywords:['gabinete contra incendio','manguera','nfpa 14','valvula de manguera','hidrante','siamesa'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Ubicación del gabinete',tipo:'texto'},
    {etiqueta:'¿Gabinete accesible y sin obstrucciones?',tipo:'si_no'},{etiqueta:'¿Manguera en buen estado, sin grietas?',tipo:'si_no'},
    {etiqueta:'¿Válvula opera sin fugas?',tipo:'si_no'},{etiqueta:'Presión en el gabinete (PSI)',tipo:'numero'},
    {etiqueta:'¿Boquilla / pitón presente y funcional?',tipo:'si_no'},{etiqueta:'¿Señalización visible?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_chimeneas_cocina',vertical:'inmuebles',nombre:'Inspección de Chimeneas y Campanas de Cocina Industrial (NFPA 96)',
   keywords:['chimenea','campana extractora','cocina industrial','nfpa 96','grasa','ductos','extraccion'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Área / Cocina evaluada',tipo:'texto'},
    {etiqueta:'¿Campana sin acumulación excesiva de grasa?',tipo:'si_no'},{etiqueta:'¿Filtros limpios y en buen estado?',tipo:'si_no'},
    {etiqueta:'¿Ductos sin obstrucciones?',tipo:'si_no'},{etiqueta:'¿Sistema de extracción funciona correctamente?',tipo:'si_no'},
    {etiqueta:'¿Sistema de supresión de incendios (si aplica) operativo?',tipo:'si_no'},
    {etiqueta:'Fecha de última limpieza profunda',tipo:'fecha'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Foto',tipo:'foto'},{etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_bomba_agua',vertical:'inmuebles',nombre:'Inspección de Bomba de Agua / Sistema Hidroneumático',
   keywords:['bomba de agua','hidroneumatico','presion de agua','tanque hidroneumatico','suministro de agua'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Identificación de la bomba',tipo:'texto'},
    {etiqueta:'Presión del sistema (PSI)',tipo:'numero'},{etiqueta:'¿Arranque y parada automática correctos?',tipo:'si_no'},
    {etiqueta:'¿Sin ruidos o vibraciones anormales?',tipo:'si_no'},{etiqueta:'¿Sin fugas visibles?',tipo:'si_no'},
    {etiqueta:'Nivel del tanque de reserva (%)',tipo:'numero'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_planta_emergencia',vertical:'inmuebles',nombre:'Inspección de Planta Eléctrica de Emergencia',
   keywords:['planta electrica','generador','emergencia','transferencia automatica','combustible','ats'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Identificación de la planta',tipo:'texto'},
    {etiqueta:'Nivel de combustible (%)',tipo:'numero'},{etiqueta:'¿Arranque en prueba exitoso?',tipo:'si_no'},
    {etiqueta:'¿Transferencia automática (ATS) funciona?',tipo:'si_no'},{etiqueta:'¿Niveles de aceite y refrigerante correctos?',tipo:'si_no'},
    {etiqueta:'¿Sin fugas ni ruidos anormales?',tipo:'si_no'},{etiqueta:'Horas de funcionamiento acumuladas',tipo:'numero'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_ascensores',vertical:'inmuebles',nombre:'Inspección de Ascensores',
   keywords:['ascensor','elevador','mantenimiento de ascensores','cabina','puertas de ascensor'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Identificación del ascensor',tipo:'texto'},
    {etiqueta:'¿Puertas abren y cierran correctamente?',tipo:'si_no'},{etiqueta:'¿Botonera e indicadores funcionan?',tipo:'si_no'},
    {etiqueta:'¿Sistema de comunicación / alarma de emergencia opera?',tipo:'si_no'},{etiqueta:'¿Iluminación de cabina adecuada?',tipo:'si_no'},
    {etiqueta:'¿Nivelación correcta en cada piso?',tipo:'si_no'},{etiqueta:'¿Certificado de mantenimiento vigente?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'ronda_vigilancia',vertical:'inmuebles',nombre:'Ronda de Vigilancia y Seguridad Física',
   keywords:['ronda','vigilancia','seguridad fisica','guarda','recorrido','novedad de seguridad'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora de la ronda',tipo:'hora_auto'},
    {etiqueta:'Ubicación / Punto de control',tipo:'ubicacion'},
    {etiqueta:'¿Puertas y accesos asegurados?',tipo:'si_no'},{etiqueta:'¿Cámaras y sistema CCTV operativos?',tipo:'si_no'},
    {etiqueta:'¿Iluminación exterior adecuada?',tipo:'si_no'},{etiqueta:'¿Novedades de seguridad?',tipo:'si_no'},
    {etiqueta:'Descripción de novedad',tipo:'textarea'},{etiqueta:'Foto',tipo:'foto'},
    {etiqueta:'Guarda responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'mantenimiento_hvac',vertical:'inmuebles',nombre:'Mantenimiento Preventivo de Aires Acondicionados (HVAC)',
   keywords:['hvac','aire acondicionado','mantenimiento preventivo','filtros','refrigerante','unidad condensadora'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Identificación del equipo',tipo:'texto'},
    {etiqueta:'Ubicación',tipo:'texto'},{etiqueta:'¿Filtros limpios o cambiados?',tipo:'si_no'},
    {etiqueta:'¿Nivel de refrigerante adecuado?',tipo:'si_no'},{etiqueta:'¿Unidad condensadora sin obstrucciones?',tipo:'si_no'},
    {etiqueta:'Temperatura de salida (°C)',tipo:'numero'},{etiqueta:'¿Sin ruidos ni vibraciones anormales?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Técnico responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'inspeccion_tanques_agua',vertical:'inmuebles',nombre:'Inspección de Tanques de Almacenamiento de Agua',
   keywords:['tanque de agua','almacenamiento de agua','potable','lavado de tanque','nivel de agua'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Identificación del tanque',tipo:'texto'},
    {etiqueta:'Nivel de agua (%)',tipo:'numero'},{etiqueta:'¿Tapa y sello en buen estado?',tipo:'si_no'},
    {etiqueta:'¿Agua sin turbidez ni olor anormal?',tipo:'si_no'},{etiqueta:'¿Estructura sin grietas ni filtraciones?',tipo:'si_no'},
    {etiqueta:'Fecha de último lavado',tipo:'fecha'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'aseo_areas_comunes',vertical:'inmuebles',nombre:'Checklist de Aseo y Limpieza de Áreas Comunes',
   keywords:['aseo','limpieza','areas comunes','lobby','baños','pasillos','jardines'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Área',tipo:'select',opciones:['Lobby / Recepción','Baños','Pasillos','Ascensores','Parqueadero','Zonas verdes','Otro']},
    {etiqueta:'¿Pisos limpios y secos?',tipo:'si_no'},{etiqueta:'¿Baños abastecidos (jabón, papel)?',tipo:'si_no'},
    {etiqueta:'¿Canecas vacías y sin desbordamiento?',tipo:'si_no'},{etiqueta:'¿Vidrios y superficies limpias?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Responsable de aseo',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  // ── Construcción Verticales (seguridad en obra + control de avance) ──
  {id:'control_acceso_obra',vertical:'construccion',nombre:'Control de Ingreso de Personal y Visitantes a Obra',
   keywords:['ingreso','acceso','obra','visitante','contratista','control de acceso','induccion','epp obligatorio'],
   campos_clave:[
    {etiqueta:'Nombre completo',tipo:'texto'},{etiqueta:'Cédula',tipo:'numero'},
    {etiqueta:'Empresa / Contratista',tipo:'texto'},{etiqueta:'Fecha de ingreso',tipo:'fecha_auto'},
    {etiqueta:'Hora de ingreso',tipo:'hora_auto'},{etiqueta:'Hora de salida',tipo:'hora'},
    {etiqueta:'Motivo de la visita',tipo:'select',opciones:['Trabajo contratado','Visita técnica','Supervisión','Entrega de materiales','Otro']},
    {etiqueta:'¿Recibió inducción de seguridad?',tipo:'si_no'},
    {etiqueta:'EPP verificado',tipo:'checkbox_multi',opciones:['Casco','Botas de seguridad','Chaleco reflectivo','Guantes','Gafas de seguridad']},
    {etiqueta:'Firma de ingreso',tipo:'firma'},
  ]},

  {id:'permiso_altura_obra',vertical:'construccion',nombre:'Permiso de Trabajo en Alturas (Obra)',norma:'Resolución 4272 de 2021 (trabajo en alturas)',
   keywords:['trabajo en alturas','andamio','arnes','linea de vida','punto de anclaje','permiso de altura','resolucion 4272'],
   campos_clave:[
    {etiqueta:'Número de permiso',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Hora de finalización',tipo:'hora'},
    {etiqueta:'Trabajador autorizado',tipo:'texto'},
    {etiqueta:'Nivel de riesgo',tipo:'select',opciones:['Riesgo I - Trabajo no rutinario','Riesgo II - Trabajo rutinario']},
    {etiqueta:'Altura de trabajo (m)',tipo:'numero'},
    {etiqueta:'Sistema de protección utilizado',tipo:'select',opciones:['Línea de vida','Andamio certificado','Plataforma elevadora','Línea de anclaje móvil']},
    {etiqueta:'¿Certificado de trabajo en alturas vigente?',tipo:'si_no'},
    {etiqueta:'¿Equipo de protección inspeccionado?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma del trabajador',tipo:'firma'},{etiqueta:'Firma del supervisor de alturas',tipo:'firma'},
  ]},

  {id:'inspeccion_andamios',vertical:'construccion',nombre:'Inspección de Andamios',
   keywords:['andamio','plataforma','base nivelada','barandas','rodapie','anclaje','scaffolding'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Ubicación / Frente de obra',tipo:'texto'},
    {etiqueta:'Tipo de andamio',tipo:'select',opciones:['Tubular','Multidireccional','Colgante','Torre móvil']},
    {etiqueta:'¿Base nivelada y estable?',tipo:'si_no'},
    {etiqueta:'¿Barandas y rodapiés instalados?',tipo:'si_no'},
    {etiqueta:'¿Anclajes asegurados?',tipo:'si_no'},
    {etiqueta:'Tarjeta de inspección visible',tipo:'select',opciones:['Verde - Apto','Roja - No apto']},
    {etiqueta:'Observaciones / Hallazgos',tipo:'textarea'},
    {etiqueta:'Fotografía del andamio',tipo:'foto'},{etiqueta:'Firma del inspector',tipo:'firma'},
  ]},

  {id:'preoperacional_maquinaria',vertical:'construccion',nombre:'Checklist Preoperacional de Maquinaria Pesada',
   keywords:['preoperacional','maquinaria','retroexcavadora','volqueta','grua','vehiculo','equipo pesado','revision diaria'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Tipo de equipo',tipo:'select',opciones:['Retroexcavadora','Volqueta','Grúa','Minicargador','Montacargas','Otro']},
    {etiqueta:'Placa / Identificación',tipo:'texto'},{etiqueta:'Operador',tipo:'texto'},
    {etiqueta:'Kilometraje / Horómetro',tipo:'numero'},
    {etiqueta:'¿Niveles de aceite y refrigerante OK?',tipo:'si_no'},
    {etiqueta:'¿Luces y alarma de reversa funcionando?',tipo:'si_no'},
    {etiqueta:'¿Frenos en buen estado?',tipo:'si_no'},
    {etiqueta:'¿Extintor a bordo y vigente?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Firma del operador',tipo:'firma'},
  ]},

  {id:'bitacora_obra',vertical:'construccion',nombre:'Bitácora Diaria de Obra',
   keywords:['bitacora','avance de obra','registro diario','actividades del dia','personal en obra','clima'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Frente de obra / Actividad',tipo:'texto'},
    {etiqueta:'Clima',tipo:'select',opciones:['Soleado','Nublado','Lluvia','Tormenta']},
    {etiqueta:'Personal en obra',tipo:'numero'},
    {etiqueta:'Actividades ejecutadas',tipo:'textarea'},{etiqueta:'Materiales recibidos',tipo:'textarea'},
    {etiqueta:'Novedades / Incidentes',tipo:'textarea'},{etiqueta:'Fotografía de avance',tipo:'foto'},
    {etiqueta:'Firma del residente de obra',tipo:'firma'},
  ]},

  {id:'inspeccion_seguridad_obra',vertical:'construccion',nombre:'Inspección de Seguridad en Obra',
   keywords:['inspeccion de seguridad','obra','orden y aseo','senalizacion','riesgo locativo','condiciones inseguras'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Frente de obra',tipo:'texto'},
    {etiqueta:'Inspector',tipo:'texto'},
    {etiqueta:'¿Señalización de riesgos visible?',tipo:'si_no'},
    {etiqueta:'¿Orden y aseo adecuados?',tipo:'si_no'},
    {etiqueta:'¿Delimitación de zonas de riesgo?',tipo:'si_no'},
    {etiqueta:'¿EPP utilizado por el personal?',tipo:'si_no'},
    {etiqueta:'Calificación general',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'Hallazgos y acciones correctivas',tipo:'textarea'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Ubicación GPS',tipo:'ubicacion'},
    {etiqueta:'Firma del inspector',tipo:'firma'},
  ]},

  {id:'entrega_avance_obra',vertical:'construccion',nombre:'Acta de Entrega de Avance / Recibo de Obra',
   keywords:['acta de entrega','avance de obra','recibo de obra','porcentaje de avance','interventoria','contratista'],
   campos_clave:[
    {etiqueta:'Número de acta',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Contrato / Proyecto',tipo:'texto'},{etiqueta:'Contratista',tipo:'texto'},
    {etiqueta:'Porcentaje de avance (%)',tipo:'numero'},{etiqueta:'Actividades entregadas',tipo:'textarea'},
    {etiqueta:'¿Cumple con especificaciones técnicas?',tipo:'si_no'},
    {etiqueta:'Observaciones de interventoría',tipo:'textarea'},{etiqueta:'Fotografía de la obra',tipo:'foto'},
    {etiqueta:'Firma del contratista',tipo:'firma'},{etiqueta:'Firma del interventor',tipo:'firma'},
  ]},

  {id:'reporte_no_conformidad_obra',vertical:'construccion',nombre:'Reporte de No Conformidad en Obra',
   keywords:['no conformidad','obra','desviacion','accion correctiva','calidad de obra','reproceso'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Frente de obra',tipo:'texto'},
    {etiqueta:'Descripción de la no conformidad',tipo:'textarea'},
    {etiqueta:'Tipo',tipo:'select',opciones:['Calidad','Seguridad','Ambiental','Cronograma']},
    {etiqueta:'Causa',tipo:'textarea'},{etiqueta:'Acción correctiva propuesta',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha límite de cierre',tipo:'fecha'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Firma de quien reporta',tipo:'firma'},
  ]},

  // ── Alimentos Verticales (INVIMA · HACCP · BPM) ───────────────
  {id:'inspeccion_sanitaria',vertical:'alimentos',nombre:'Inspección Sanitaria / Higiene',norma:'Resolución 2674 de 2013 (INVIMA)',
   keywords:['sanitaria','higiene','alimento','limpieza','desinfeccion','plagas','temperatura','inocuidad','establecimiento','bpm'],
   campos_clave:[
    {etiqueta:'Nombre del establecimiento',tipo:'texto'},{etiqueta:'Fecha de inspección',tipo:'fecha_auto'},
    {etiqueta:'Tipo de establecimiento',tipo:'select'},{etiqueta:'Temperatura de almacenamiento (°C)',tipo:'numero'},
    {etiqueta:'Condición de limpieza',tipo:'radio',opciones:['Deficiente','Regular','Bueno','Muy Bueno','Excelente']},
    {etiqueta:'¿Control de plagas vigente?',tipo:'si_no'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Fotografía de evidencia',tipo:'foto'},{etiqueta:'Firma del inspector',tipo:'firma'},
    {etiqueta:'Ubicación GPS',tipo:'ubicacion'},
  ]},
  {id:'control_temperatura_haccp',vertical:'alimentos',nombre:'Control de Temperatura HACCP (Refrigeración/Congelación)',norma:'Resolución 2674/2013 · HACCP',
   keywords:['temperatura','refrigeracion','congelacion','haccp','nevera','cuarto frio','punto critico de control'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Hora de registro',tipo:'hora_auto'},
    {etiqueta:'Equipo / Cuarto frío',tipo:'select',opciones:['Refrigerador 1','Refrigerador 2','Congelador','Cuarto frío','Vitrina']},
    {etiqueta:'Temperatura registrada (°C)',tipo:'numero'},
    {etiqueta:'Rango permitido',tipo:'texto'},
    {etiqueta:'¿Dentro del rango permitido?',tipo:'si_no'},
    {etiqueta:'Acción correctiva si aplica',tipo:'textarea'},
    {etiqueta:'Responsable del registro',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'limpieza_desinfeccion',vertical:'alimentos',nombre:'Registro de Limpieza y Desinfección',norma:'Resolución 2674 de 2013 (BPM)',
   keywords:['limpieza','desinfeccion','sanitizacion','superficie','utensilios','area de produccion','quimico utilizado'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Área / Equipo',tipo:'select',opciones:['Cocina','Área de producción','Baños','Almacén','Utensilios','Superficies de contacto']},
    {etiqueta:'Producto desinfectante utilizado',tipo:'texto'},{etiqueta:'Concentración',tipo:'texto'},
    {etiqueta:'¿Limpieza realizada conforme al procedimiento?',tipo:'si_no'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'control_plagas',vertical:'alimentos',nombre:'Control de Plagas (MIP)',norma:'Resolución 2674 de 2013 (Plan de saneamiento)',
   keywords:['plagas','roedores','insectos','mip','manejo integrado de plagas','trampa','cebo','fumigacion'],
   campos_clave:[
    {etiqueta:'Fecha de inspección',tipo:'fecha_auto'},{etiqueta:'Empresa de control de plagas',tipo:'texto'},
    {etiqueta:'Tipo de plaga monitoreada',tipo:'select',opciones:['Roedores','Insectos rastreros','Insectos voladores','Otro']},
    {etiqueta:'¿Evidencia de actividad de plagas?',tipo:'si_no'},
    {etiqueta:'Estaciones / trampas revisadas',tipo:'numero'},
    {etiqueta:'Acción tomada',tipo:'select',opciones:['Ninguna','Cebo repuesto','Fumigación','Sellado de puntos de entrada']},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Fotografía de evidencia',tipo:'foto'},
    {etiqueta:'Firma del técnico',tipo:'firma'},
  ]},

  {id:'recepcion_materia_prima',vertical:'alimentos',nombre:'Recepción de Materia Prima / Proveedores',
   keywords:['recepcion','materia prima','proveedor','insumo','fecha de vencimiento','lote','certificado de calidad'],
   campos_clave:[
    {etiqueta:'Fecha de recepción',tipo:'fecha_auto'},{etiqueta:'Proveedor',tipo:'texto'},
    {etiqueta:'Producto recibido',tipo:'texto'},{etiqueta:'Lote',tipo:'texto'},
    {etiqueta:'Cantidad',tipo:'numero'},{etiqueta:'Fecha de vencimiento',tipo:'fecha'},
    {etiqueta:'Temperatura de recepción (°C)',tipo:'numero'},
    {etiqueta:'¿Empaque en buen estado?',tipo:'si_no'},{etiqueta:'¿Cumple con ficha técnica?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Firma de quien recibe',tipo:'firma'},
  ]},

  {id:'trazabilidad_lote',vertical:'alimentos',nombre:'Trazabilidad de Lote / Producto Terminado',
   keywords:['trazabilidad','lote','producto terminado','fecha de produccion','fecha de vencimiento','destino','despacho'],
   campos_clave:[
    {etiqueta:'Fecha de producción',tipo:'fecha_auto'},{etiqueta:'Producto',tipo:'texto'},
    {etiqueta:'Número de lote',tipo:'texto'},{etiqueta:'Cantidad producida',tipo:'numero'},
    {etiqueta:'Fecha de vencimiento',tipo:'fecha'},{etiqueta:'Materias primas utilizadas',tipo:'textarea'},
    {etiqueta:'Destino / Cliente',tipo:'texto'},{etiqueta:'Responsable de producción',tipo:'texto'},
    {etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'capacitacion_manipulacion',vertical:'alimentos',nombre:'Capacitación en Manipulación de Alimentos',
   keywords:['manipulacion de alimentos','carnet de manipulacion','curso','higiene del manipulador','capacitacion sanitaria'],
   campos_clave:[
    {etiqueta:'Nombre del manipulador',tipo:'texto'},{etiqueta:'Cédula',tipo:'numero'},
    {etiqueta:'Cargo',tipo:'select',opciones:['Cocinero','Mesero','Auxiliar de cocina','Operario de producción','Otro']},
    {etiqueta:'Fecha de capacitación',tipo:'fecha_auto'},
    {etiqueta:'Tema de la capacitación',tipo:'select',opciones:['Buenas Prácticas de Manufactura (BPM)','HACCP','Higiene personal','Manejo de alérgenos','Otro']},
    {etiqueta:'Capacitador',tipo:'texto'},{etiqueta:'¿Aprobó la evaluación?',tipo:'si_no'},
    {etiqueta:'Vigencia del carné',tipo:'fecha'},{etiqueta:'Firma del manipulador',tipo:'firma'},
  ]},

  {id:'no_conformidad_invima',vertical:'alimentos',nombre:'No Conformidad y Acción Correctiva (Auditoría INVIMA)',
   keywords:['no conformidad','invima','auditoria','hallazgo','accion correctiva','plan de mejora','acta de visita'],
   campos_clave:[
    {etiqueta:'Fecha de la auditoría',tipo:'fecha_auto'},
    {etiqueta:'Tipo de auditoría',tipo:'select',opciones:['INVIMA','Interna','Cliente','Certificación']},
    {etiqueta:'Hallazgo / No conformidad',tipo:'textarea'},
    {etiqueta:'Clasificación',tipo:'select',opciones:['Crítica','Mayor','Menor','Observación']},
    {etiqueta:'Causa raíz',tipo:'textarea'},{etiqueta:'Acción correctiva',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Fecha límite de cierre',tipo:'fecha'},
    {etiqueta:'Evidencia fotográfica',tipo:'foto'},{etiqueta:'Firma del responsable de calidad',tipo:'firma'},
  ]},

  // ── Salud Verticales (clínicas, IPS, laboratorios) ────────────
  {id:'triage_urgencias',vertical:'salud',nombre:'Triage de Urgencias',
   keywords:['triage','urgencias','clasificacion','prioridad','paciente','signos vitales','motivo de consulta'],
   campos_clave:[
    {etiqueta:'Nombre del paciente',tipo:'texto'},{etiqueta:'Documento de identidad',tipo:'numero'},
    {etiqueta:'Fecha de ingreso',tipo:'fecha_auto'},{etiqueta:'Hora de ingreso',tipo:'hora_auto'},
    {etiqueta:'Motivo de consulta',tipo:'textarea'},
    {etiqueta:'Presión arterial',tipo:'texto'},{etiqueta:'Frecuencia cardíaca',tipo:'numero'},
    {etiqueta:'Frecuencia respiratoria',tipo:'numero'},{etiqueta:'Temperatura (°C)',tipo:'numero'},
    {etiqueta:'Saturación de oxígeno (%)',tipo:'numero'},
    {etiqueta:'Nivel de triage',tipo:'select',opciones:['I - Resucitación','II - Emergencia','III - Urgencia','IV - Urgencia menor','V - No urgencia']},
    {etiqueta:'Profesional que clasifica',tipo:'texto'},{etiqueta:'Firma del profesional',tipo:'firma'},
  ]},

  {id:'consentimiento_informado',vertical:'salud',nombre:'Consentimiento Informado',
   keywords:['consentimiento informado','procedimiento','riesgos','autorizacion','paciente','representante legal'],
   campos_clave:[
    {etiqueta:'Nombre del paciente',tipo:'texto'},{etiqueta:'Documento de identidad',tipo:'numero'},
    {etiqueta:'Procedimiento a realizar',tipo:'texto'},{etiqueta:'Médico tratante',tipo:'texto'},
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'¿Riesgos explicados al paciente?',tipo:'si_no'},
    {etiqueta:'¿Paciente autoriza el procedimiento?',tipo:'si_no'},
    {etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma del paciente / representante',tipo:'firma'},{etiqueta:'Firma del médico',tipo:'firma'},
  ]},

  {id:'historia_clinica_ingreso',vertical:'salud',nombre:'Historia Clínica — Ingreso',
   keywords:['historia clinica','ingreso','antecedentes','anamnesis','examen fisico','diagnostico'],
   campos_clave:[
    {etiqueta:'Nombre del paciente',tipo:'texto'},{etiqueta:'Documento de identidad',tipo:'numero'},
    {etiqueta:'Fecha de ingreso',tipo:'fecha_auto'},{etiqueta:'Edad',tipo:'numero'},
    {etiqueta:'Motivo de consulta',tipo:'textarea'},{etiqueta:'Antecedentes personales',tipo:'textarea'},
    {etiqueta:'Antecedentes familiares',tipo:'textarea'},{etiqueta:'Examen físico',tipo:'textarea'},
    {etiqueta:'Diagnóstico',tipo:'textarea'},{etiqueta:'Plan de manejo',tipo:'textarea'},
    {etiqueta:'Médico responsable',tipo:'texto'},{etiqueta:'Firma del médico',tipo:'firma'},
  ]},

  {id:'esterilizacion_equipos',vertical:'salud',nombre:'Control de Esterilización de Equipos e Instrumental',norma:'Resolución 3100 de 2019',
   keywords:['esterilizacion','autoclave','instrumental','indicador biologico','indicador quimico','lote de esterilizacion'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Equipo / Autoclave',tipo:'texto'},
    {etiqueta:'Número de lote',tipo:'texto'},
    {etiqueta:'Tipo de carga',tipo:'select',opciones:['Instrumental quirúrgico','Textiles','Material de curación','Otro']},
    {etiqueta:'Temperatura alcanzada (°C)',tipo:'numero'},{etiqueta:'Tiempo de exposición (min)',tipo:'numero'},
    {etiqueta:'¿Indicador químico correcto?',tipo:'si_no'},{etiqueta:'¿Indicador biológico correcto?',tipo:'si_no'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'manejo_residuos_hospitalarios',vertical:'salud',nombre:'Manejo de Residuos Hospitalarios (PGIRASA)',norma:'Decreto 351 de 2014 (PGIRASA)',
   keywords:['residuos hospitalarios','pgirasa','peligrosos','cortopunzante','anatomopatologico','recoleccion','segregacion'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Área generadora',tipo:'select',opciones:['Urgencias','Hospitalización','Cirugía','Laboratorio','Consulta externa','Otro']},
    {etiqueta:'Tipo de residuo',tipo:'select',opciones:['Biosanitario','Cortopunzante','Anatomopatológico','Químico','Ordinario']},
    {etiqueta:'Cantidad (kg)',tipo:'numero'},
    {etiqueta:'¿Segregación correcta en la fuente?',tipo:'si_no'},{etiqueta:'¿Rotulado conforme a la norma?',tipo:'si_no'},
    {etiqueta:'Responsable de recolección',tipo:'texto'},{etiqueta:'Observaciones',tipo:'textarea'},
    {etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'control_medicamentos',vertical:'salud',nombre:'Control de Medicamentos de Control Especial',
   keywords:['medicamentos','control especial','psicotropico','estupefaciente','custodia','farmacia','kardex'],
   campos_clave:[
    {etiqueta:'Fecha',tipo:'fecha_auto'},{etiqueta:'Medicamento',tipo:'texto'},{etiqueta:'Lote',tipo:'texto'},
    {etiqueta:'Cantidad en existencia',tipo:'numero'},{etiqueta:'Cantidad dispensada',tipo:'numero'},
    {etiqueta:'Paciente / Servicio destino',tipo:'texto'},{etiqueta:'Responsable de farmacia',tipo:'texto'},
    {etiqueta:'Firma de quien dispensa',tipo:'firma'},{etiqueta:'Firma de quien recibe',tipo:'firma'},
  ]},

  {id:'inspeccion_habilitacion',vertical:'salud',nombre:'Lista de Verificación de Habilitación de Servicios de Salud',norma:'Resolución 3100 de 2019',
   keywords:['habilitacion','estandares','infraestructura','dotacion','autoevaluacion','servicio de salud','calidad'],
   campos_clave:[
    {etiqueta:'Servicio evaluado',tipo:'texto'},{etiqueta:'Fecha de autoevaluación',tipo:'fecha_auto'},
    {etiqueta:'Estándar de infraestructura',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Estándar de dotación',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Estándar de procesos prioritarios',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Estándar de historia clínica',tipo:'select',opciones:['Cumple','No cumple','Cumple parcialmente']},
    {etiqueta:'Hallazgos',tipo:'textarea'},{etiqueta:'Plan de mejoramiento',tipo:'textarea'},
    {etiqueta:'Responsable',tipo:'texto'},{etiqueta:'Firma',tipo:'firma'},
  ]},

  {id:'reporte_evento_adverso',vertical:'salud',nombre:'Reporte de Evento Adverso / Seguridad del Paciente',
   keywords:['evento adverso','seguridad del paciente','incidente','near miss','analisis causa raiz','centinela'],
   campos_clave:[
    {etiqueta:'Fecha del evento',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Servicio',tipo:'select',opciones:['Urgencias','Hospitalización','Cirugía','UCI','Consulta externa','Otro']},
    {etiqueta:'Tipo de evento',tipo:'select',opciones:['Evento adverso','Incidente (near miss)','Evento centinela']},
    {etiqueta:'Descripción del evento',tipo:'textarea'},{etiqueta:'¿Se notificó a la familia?',tipo:'si_no'},
    {etiqueta:'Acción inmediata tomada',tipo:'textarea'},{etiqueta:'Responsable del análisis',tipo:'texto'},
    {etiqueta:'Firma',tipo:'firma'},
  ]},

  // ── General (formatos administrativos genéricos, sin vertical específica) ──
  {id:'acta_reunion',vertical:'general',nombre:'Acta de Reunión',
   keywords:['reunion','acta','acuerdo','compromiso','asistente','orden del dia','seguimiento','responsable'],
   campos_clave:[
    {etiqueta:'Objeto / Asunto de la reunión',tipo:'texto'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Hora de inicio',tipo:'hora_auto'},{etiqueta:'Lugar / Modalidad',tipo:'select',opciones:['Presencial','Virtual','Híbrida']},
    {etiqueta:'Nombre del asistente',tipo:'texto'},
    {etiqueta:'Compromisos / Acuerdos',tipo:'textarea'},{etiqueta:'Responsable del compromiso',tipo:'texto'},
    {etiqueta:'Fecha límite de cumplimiento',tipo:'fecha_auto'},{etiqueta:'Firma del secretario',tipo:'firma'},
  ]},
  {id:'orden_trabajo',vertical:'general',nombre:'Orden de Trabajo / Servicio',
   keywords:['orden','trabajo','servicio','mantenimiento','correctivo','preventivo','tecnico','falla','equipo','actividades realizadas'],
   campos_clave:[
    {etiqueta:'Número de orden',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Cliente / Empresa',tipo:'texto'},
    {etiqueta:'Tipo de mantenimiento',tipo:'select',opciones:['Correctivo','Preventivo','Predictivo','Instalación']},
    {etiqueta:'Descripción del problema',tipo:'textarea'},{etiqueta:'Actividades realizadas',tipo:'textarea'},
    {etiqueta:'Repuestos / Materiales',tipo:'textarea'},{etiqueta:'Técnico responsable',tipo:'texto'},
    {etiqueta:'Fotografía antes',tipo:'foto'},{etiqueta:'Fotografía después',tipo:'foto'},
    {etiqueta:'Firma del cliente',tipo:'firma'},
  ]},
  {id:'evaluacion_desempeno',vertical:'general',nombre:'Evaluación de Desempeño',
   keywords:['desempeno','evaluacion','competencia','indicador','meta','logro','colaborador','periodo','resultado','calificacion'],
   campos_clave:[
    {etiqueta:'Nombre del colaborador',tipo:'texto'},{etiqueta:'Cargo',tipo:'select'},
    {etiqueta:'Área / Departamento',tipo:'select'},{etiqueta:'Periodo evaluado',tipo:'texto'},
    {etiqueta:'Calificación general',tipo:'radio',opciones:['1 - Deficiente','2 - Regular','3 - Bueno','4 - Muy Bueno','5 - Excelente']},
    {etiqueta:'Logros del periodo',tipo:'textarea'},{etiqueta:'Oportunidades de mejora',tipo:'textarea'},
    {etiqueta:'Plan de desarrollo',tipo:'textarea'},{etiqueta:'Firma del evaluado',tipo:'firma'},
    {etiqueta:'Firma del evaluador',tipo:'firma'},
  ]},
  {id:'visita_comercial',vertical:'general',nombre:'Reporte de Visita Comercial',
   keywords:['visita','comercial','cliente','prospecto','cotizacion','oportunidad','venta','negocio','seguimiento'],
   campos_clave:[
    {etiqueta:'Fecha de visita',tipo:'fecha_auto'},{etiqueta:'Hora',tipo:'hora_auto'},
    {etiqueta:'Nombre del cliente / empresa',tipo:'texto'},{etiqueta:'Contacto / Persona atendida',tipo:'texto'},
    {etiqueta:'Teléfono',tipo:'telefono'},{etiqueta:'Correo electrónico',tipo:'email'},
    {etiqueta:'Objetivo de la visita',tipo:'textarea'},
    {etiqueta:'Resultado',tipo:'select',opciones:['Interesado','No interesado','Requiere seguimiento','Cotización enviada','Negocio cerrado']},
    {etiqueta:'Próximos pasos',tipo:'textarea'},{etiqueta:'Ubicación GPS',tipo:'ubicacion'},
    {etiqueta:'Firma del vendedor',tipo:'firma'},
  ]},
  {id:'solicitud_compra',vertical:'general',nombre:'Solicitud de Compra / Pedido',
   keywords:['solicitud','compra','pedido','requisicion','proveedor','cotizacion','articulo','cantidad','precio'],
   campos_clave:[
    {etiqueta:'Número de solicitud',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Solicitante',tipo:'texto'},{etiqueta:'Área / Departamento',tipo:'select'},
    {etiqueta:'Descripción del artículo',tipo:'texto'},{etiqueta:'Cantidad',tipo:'numero'},
    {etiqueta:'Unidad de medida',tipo:'select',opciones:['Unidad','Caja','Kg','Litro','Metro','Paquete']},
    {etiqueta:'Justificación / Uso',tipo:'textarea'},{etiqueta:'Firma del solicitante',tipo:'firma'},
    {etiqueta:'Aprobado por',tipo:'firma'},
  ]},
  {id:'entrega_recibo',vertical:'general',nombre:'Acta de Entrega / Recibo de Bienes',
   keywords:['entrega','recibo','bien','activo','devolucion','recibido por','entregado por','estado del bien'],
   campos_clave:[
    {etiqueta:'Fecha de entrega',tipo:'fecha_auto'},{etiqueta:'Descripción del bien',tipo:'texto'},
    {etiqueta:'Serial / Código',tipo:'texto'},{etiqueta:'Cantidad',tipo:'numero'},
    {etiqueta:'Estado del bien',tipo:'select',opciones:['Nuevo','Bueno','Regular','Malo']},
    {etiqueta:'Entregado por',tipo:'texto'},{etiqueta:'Recibido por',tipo:'texto'},
    {etiqueta:'Observaciones',tipo:'textarea'},{etiqueta:'Fotografía del bien',tipo:'foto'},
    {etiqueta:'Firma de quien entrega',tipo:'firma'},{etiqueta:'Firma de quien recibe',tipo:'firma'},
  ]},
  {id:'hoja_de_vida',vertical:'general',nombre:'Hoja de Vida / Solicitud de Empleo',
   keywords:['hoja de vida','curriculum','empleo','aspirante','candidato','experiencia','educacion','referencias','salario'],
   campos_clave:[
    {etiqueta:'Nombres y apellidos',tipo:'texto'},{etiqueta:'Número de cédula',tipo:'numero'},
    {etiqueta:'Fecha de nacimiento',tipo:'fecha'},{etiqueta:'Teléfono celular',tipo:'telefono'},
    {etiqueta:'Correo electrónico',tipo:'email'},
    {etiqueta:'Nivel educativo',tipo:'select',opciones:['Bachillerato','Técnico','Tecnólogo','Universitario','Especialización','Maestría']},
    {etiqueta:'Cargo aspirado',tipo:'texto'},{etiqueta:'Experiencia laboral previa',tipo:'textarea'},
    {etiqueta:'Salario aspirado',tipo:'numero'},{etiqueta:'Fotografía',tipo:'foto'},
    {etiqueta:'Firma del aspirante',tipo:'firma'},
  ]},
  {id:'calibracion',vertical:'general',nombre:'Registro de Calibración / Mantenimiento de Equipos',
   keywords:['calibracion','instrumento','patron','verificacion','tolerancia','medicion','resultado de calibracion'],
   campos_clave:[
    {etiqueta:'Número de registro',tipo:'numero'},{etiqueta:'Fecha',tipo:'fecha_auto'},
    {etiqueta:'Equipo / Instrumento',tipo:'texto'},{etiqueta:'Serial / Código',tipo:'texto'},
    {etiqueta:'Tipo de mantenimiento',tipo:'select',opciones:['Preventivo','Correctivo','Calibración','Verificación']},
    {etiqueta:'Resultado de la calibración',tipo:'select',opciones:['Conforme','No conforme','Fuera de tolerancia']},
    {etiqueta:'Próxima calibración',tipo:'fecha'},{etiqueta:'Observaciones técnicas',tipo:'textarea'},
    {etiqueta:'Técnico responsable',tipo:'texto'},{etiqueta:'Firma del técnico',tipo:'firma'},
  ]},
];
